#!/usr/bin/env bun
// PocketBun-only: writes generated Jekyll data for the docs header version.

import { mkdir } from "node:fs/promises";
import { dirname } from "node:path";

type PackageJson = {
  version?: unknown;
};

const outputPath = "docs/_data/pocketbun.yml";
const checkOnly = process.argv.includes("--check");

function fail(message: string): never {
  throw new Error(message);
}

const packageJson = (await Bun.file("package.json").json()) as PackageJson;
if (typeof packageJson.version !== "string") {
  fail("Missing or invalid package.json version.");
}

const version = packageJson.version;
const content = `# Generated by scripts/docs/sync_docs_version.ts from package.json.\nversion: ${JSON.stringify(version)}\n`;

if (checkOnly) {
  const existing = await Bun.file(outputPath).text();
  if (existing !== content) {
    fail(`${outputPath} is stale. Run: bun run docs:version`);
  }
  console.log(`Docs version metadata is up to date: PocketBun ${version}`);
} else {
  await mkdir(dirname(outputPath), { recursive: true });
  await Bun.write(outputPath, content);
  console.log(`Wrote docs version metadata: PocketBun ${version}`);
}
