// Ported from pocketbase/apis/backup_test.go

import { describe, it } from "bun:test";
import type { ApiScenario } from "../tests/api.ts";
import type { TestApp } from "../tests/app.ts";
import { runApiScenario } from "../tests/api.ts";
import { DefaultMaxBodySize } from "./middlewares_body_limit.ts";

const regularUserToken =
  "eyJhbGciOiJIUzI1NiJ9.eyJpZCI6IjRxMXhsY2xtZmxva3UzMyIsInR5cGUiOiJhdXRoIiwiY29sbGVjdGlvbklkIjoiX3BiX3VzZXJzX2F1dGhfIiwiZXhwIjoyNTI0NjA0NDYxLCJyZWZyZXNoYWJsZSI6dHJ1ZX0.ZT3F0Z3iM-xbGgSG3LEKiEzHrPHr8t8IuHLZGGNuxLo";

const superuserToken =
  "eyJhbGciOiJIUzI1NiJ9.eyJpZCI6InN5d2JoZWNuaDQ2cmhtMCIsInR5cGUiOiJhdXRoIiwiY29sbGVjdGlvbklkIjoicGJjXzMxNDI2MzU4MjMiLCJleHAiOjI1MjQ2MDQ0NjEsInJlZnJlc2hhYmxlIjp0cnVlfQ.UXgO3j-0BumcugrFjbd7j0M4MQvbrLggLlcu_YNGjoY";

const recordFileToken =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjRxMXhsY2xtZmxva3UzMyIsImV4cCI6MjUyNDYwNDQ2MSwidHlwZSI6ImZpbGUiLCJjb2xsZWN0aW9uSWQiOiJfcGJfdXNlcnNfYXV0aF8ifQ.nSTLuCPcGpWn2K2l-BFkC3Vlzc-ZTDPByYq8dN1oPSo";

const superuserAuthToken =
  "eyJhbGciOiJIUzI1NiJ9.eyJpZCI6InN5d2JoZWNuaDQ2cmhtMCIsInR5cGUiOiJhdXRoIiwiY29sbGVjdGlvbklkIjoicGJjXzMxNDI2MzU4MjMiLCJleHAiOjI1MjQ2MDQ0NjEsInJlZnJlc2hhYmxlIjp0cnVlfQ.UXgO3j-0BumcugrFjbd7j0M4MQvbrLggLlcu_YNGjoY";

const superuserFileToken =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6InN5d2JoZWNuaDQ2cmhtMCIsImV4cCI6MjUyNDYwNDQ2MSwidHlwZSI6ImZpbGUiLCJjb2xsZWN0aW9uSWQiOiJwYmNfMzE0MjYzNTgyMyJ9.Lupz541xRvrktwkrl55p5pPCF77T69ZRsohsIcb2dxc";

const expiredSuperuserFileToken =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6InN5d2JoZWNuaDQ2cmhtMCIsImV4cCI6MTY0MDk5MTY2MSwidHlwZSI6ImZpbGUiLCJjb2xsZWN0aW9uSWQiOiJwYmNfMzE0MjYzNTgyMyJ9.nqqtqpPhxU0045F4XP_ruAkzAidYBc5oPy9ErN3XBq0";

const { body: uploadBody1, contentType: uploadContentType1 } = buildMultipartBody();
const { body: uploadBody2, contentType: uploadContentType2 } = buildMultipartBody();
const { body: uploadBody3, contentType: uploadContentType3 } = buildMultipartBody();
const { body: uploadBody4, contentType: uploadContentType4 } = buildMultipartBody();

const scenarios: ApiScenario[] = [
  {
    name: "backups list unauthorized",
    method: "GET",
    url: "/api/backups",
    beforeTest: async (app) => {
      await createTestBackups(app);
    },
    expectedStatus: 401,
    expectedContent: ['"data":{}'],
    expectedEvents: { "*": 0 },
  },
  {
    name: "backups list authorized as regular user",
    method: "GET",
    url: "/api/backups",
    headers: { Authorization: regularUserToken },
    beforeTest: async (app) => {
      await createTestBackups(app);
    },
    expectedStatus: 403,
    expectedContent: ['"data":{}'],
    expectedEvents: { "*": 0 },
  },
  {
    name: "backups list authorized as superuser (empty list)",
    method: "GET",
    url: "/api/backups",
    headers: { Authorization: superuserToken },
    expectedStatus: 200,
    expectedContent: ["[]"],
    expectedEvents: { "*": 0 },
  },
  {
    name: "backups list authorized as superuser",
    method: "GET",
    url: "/api/backups",
    headers: { Authorization: superuserToken },
    beforeTest: async (app) => {
      await createTestBackups(app);
    },
    expectedStatus: 200,
    expectedContent: ['"key":"test1.zip"', '"key":"test2.zip"', '"key":"test3.zip"'],
    expectedEvents: { "*": 0 },
  },
  {
    name: "backups create unauthorized",
    method: "POST",
    url: "/api/backups",
    afterTest: async (app) => {
      await ensureNoBackups(app);
    },
    expectedStatus: 401,
    expectedContent: ['"data":{}'],
    expectedEvents: { "*": 0 },
  },
  {
    name: "backups create authorized as regular user",
    method: "POST",
    url: "/api/backups",
    headers: { Authorization: regularUserToken },
    afterTest: async (app) => {
      await ensureNoBackups(app);
    },
    expectedStatus: 403,
    expectedContent: ['"data":{}'],
    expectedEvents: { "*": 0 },
  },
  {
    name: "backups create authorized as superuser (pending backup)",
    method: "POST",
    url: "/api/backups",
    headers: { Authorization: superuserToken },
    beforeTest: (app) => {
      app.store().set("@activeBackup", "");
    },
    afterTest: async (app) => {
      await ensureNoBackups(app);
    },
    expectedStatus: 400,
    expectedContent: ['"data":{}'],
    expectedEvents: { "*": 0 },
  },
  {
    name: "backups create authorized as superuser (autogenerated name)",
    method: "POST",
    url: "/api/backups",
    headers: { Authorization: superuserToken },
    afterTest: async (app) => {
      const files = await getBackupFiles(app);
      if (files.length !== 1) {
        throw new Error(`Expected 1 backup file, got ${files.length}`);
      }
      const first = files[0];
      if (!first) {
        throw new Error("Expected backup file, got none");
      }
      if (!first.Key.startsWith("pb_backup_")) {
        throw new Error(`Expected backup file with prefix "pb_backup_", got ${first.Key}`);
      }
    },
    expectedStatus: 204,
    expectedEvents: { "*": 0, OnBackupCreate: 1 },
  },
  {
    name: "backups create authorized as superuser (invalid name)",
    method: "POST",
    url: "/api/backups",
    headers: { Authorization: superuserToken },
    body: JSON.stringify({ name: "!test.zip" }),
    afterTest: async (app) => {
      await ensureNoBackups(app);
    },
    expectedStatus: 400,
    expectedContent: ['"data":{', '"name":{"code":"validation_match_invalid"'],
    expectedEvents: { "*": 0 },
  },
  {
    name: "backups create authorized as superuser (valid name)",
    method: "POST",
    url: "/api/backups",
    headers: { Authorization: superuserToken },
    body: JSON.stringify({ name: "test.zip" }),
    afterTest: async (app) => {
      const files = await getBackupFiles(app);
      if (files.length !== 1) {
        throw new Error(`Expected 1 backup file, got ${files.length}`);
      }
      const first = files[0];
      if (!first) {
        throw new Error("Expected backup file, got none");
      }
      if (first.Key !== "test.zip") {
        throw new Error(`Expected backup file "test.zip", got ${first.Key}`);
      }
    },
    expectedStatus: 204,
    expectedEvents: { "*": 0, OnBackupCreate: 1 },
  },
  {
    name: "backup upload unauthorized",
    method: "POST",
    url: "/api/backups/upload",
    body: uploadBody1,
    headers: { "Content-Type": uploadContentType1 },
    afterTest: async (app) => {
      await ensureNoBackups(app);
    },
    expectedStatus: 401,
    expectedContent: ['"data":{}'],
    expectedEvents: { "*": 0 },
  },
  {
    name: "backup upload authorized as regular user",
    method: "POST",
    url: "/api/backups/upload",
    body: uploadBody2,
    headers: { "Content-Type": uploadContentType2, Authorization: regularUserToken },
    afterTest: async (app) => {
      await ensureNoBackups(app);
    },
    expectedStatus: 403,
    expectedContent: ['"data":{}'],
    expectedEvents: { "*": 0 },
  },
  {
    name: "backup upload authorized as superuser (missing file)",
    method: "POST",
    url: "/api/backups/upload",
    headers: { Authorization: superuserToken },
    afterTest: async (app) => {
      await ensureNoBackups(app);
    },
    expectedStatus: 400,
    expectedContent: ['"data":{'],
    expectedEvents: { "*": 0 },
  },
  {
    name: "backup upload authorized as superuser (existing backup name)",
    method: "POST",
    url: "/api/backups/upload",
    body: uploadBody3,
    headers: { "Content-Type": uploadContentType3, Authorization: superuserToken },
    beforeTest: async (app) => {
      await using fsys = app.NewBackupsFilesystem();
      await fsys.Upload(new TextEncoder().encode("123"), "test");
    },
    afterTest: async (app) => {
      const files = await getBackupFiles(app);
      if (files.length !== 1) {
        throw new Error(`Expected 1 backup file, got ${files.length}`);
      }
    },
    expectedStatus: 400,
    expectedContent: ['"data":{"file":{'],
    expectedEvents: { "*": 0 },
  },
  {
    name: "backup upload authorized as superuser (valid file)",
    method: "POST",
    url: "/api/backups/upload",
    body: uploadBody4,
    headers: { "Content-Type": uploadContentType4, Authorization: superuserToken },
    afterTest: async (app) => {
      const files = await getBackupFiles(app);
      if (files.length !== 1) {
        throw new Error(`Expected 1 backup file, got ${files.length}`);
      }
    },
    expectedStatus: 204,
    expectedEvents: { "*": 0 },
  },
  {
    name: "backup upload body limit skipped",
    method: "POST",
    url: "/api/backups/upload",
    body: new Uint8Array(DefaultMaxBodySize + 100),
    headers: { Authorization: superuserToken },
    expectedStatus: 400,
    expectedContent: ['"data":{'],
    notExpectedContent: ["entity too large"],
    expectedEvents: { "*": 0 },
  },
  {
    name: "backups download unauthorized",
    method: "GET",
    url: "/api/backups/test1.zip",
    beforeTest: async (app) => {
      await createTestBackups(app);
    },
    expectedStatus: 403,
    expectedContent: ['"data":{}'],
    expectedEvents: { "*": 0 },
  },
  {
    name: "backups download with record auth header",
    method: "GET",
    url: "/api/backups/test1.zip",
    headers: { Authorization: regularUserToken },
    beforeTest: async (app) => {
      await createTestBackups(app);
    },
    expectedStatus: 403,
    expectedContent: ['"data":{}'],
    expectedEvents: { "*": 0 },
  },
  {
    name: "backups download with superuser auth header",
    method: "GET",
    url: "/api/backups/test1.zip",
    headers: { Authorization: superuserAuthToken },
    beforeTest: async (app) => {
      await createTestBackups(app);
    },
    expectedStatus: 403,
    expectedContent: ['"data":{}'],
    expectedEvents: { "*": 0 },
  },
  {
    name: "backups download with empty token",
    method: "GET",
    url: "/api/backups/test1.zip?token=",
    beforeTest: async (app) => {
      await createTestBackups(app);
    },
    expectedStatus: 403,
    expectedContent: ['"data":{}'],
    expectedEvents: { "*": 0 },
  },
  {
    name: "backups download with record auth token",
    method: "GET",
    url: `/api/backups/test1.zip?token=${regularUserToken}`,
    beforeTest: async (app) => {
      await createTestBackups(app);
    },
    expectedStatus: 403,
    expectedContent: ['"data":{}'],
    expectedEvents: { "*": 0 },
  },
  {
    name: "backups download with record file token",
    method: "GET",
    url: `/api/backups/test1.zip?token=${recordFileToken}`,
    beforeTest: async (app) => {
      await createTestBackups(app);
    },
    expectedStatus: 403,
    expectedContent: ['"data":{}'],
    expectedEvents: { "*": 0 },
  },
  {
    name: "backups download with superuser auth token",
    method: "GET",
    url: `/api/backups/test1.zip?token=${superuserAuthToken}`,
    beforeTest: async (app) => {
      await createTestBackups(app);
    },
    expectedStatus: 403,
    expectedContent: ['"data":{}'],
    expectedEvents: { "*": 0 },
  },
  {
    name: "backups download with expired superuser file token",
    method: "GET",
    url: `/api/backups/test1.zip?token=${expiredSuperuserFileToken}`,
    beforeTest: async (app) => {
      await createTestBackups(app);
    },
    expectedStatus: 403,
    expectedContent: ['"data":{}'],
    expectedEvents: { "*": 0 },
  },
  {
    name: "backups download with valid superuser file token but missing backup name",
    method: "GET",
    url: `/api/backups/missing?token=${superuserFileToken}`,
    beforeTest: async (app) => {
      await createTestBackups(app);
    },
    expectedStatus: 404,
    expectedContent: ['"data":{}'],
    expectedEvents: { "*": 0 },
  },
  {
    name: "backups download with valid superuser file token",
    method: "GET",
    url: `/api/backups/test1.zip?token=${superuserFileToken}`,
    beforeTest: async (app) => {
      await createTestBackups(app);
    },
    expectedStatus: 200,
    expectedContent: ["storage/", "data.db", "auxiliary.db"],
    expectedEvents: { "*": 0 },
  },
  {
    name: "backups download with valid superuser file token and escaped name",
    method: "GET",
    url: `/api/backups/%40test4.zip?token=${superuserFileToken}`,
    beforeTest: async (app) => {
      await createTestBackups(app);
    },
    expectedStatus: 200,
    expectedContent: ["storage/", "data.db", "auxiliary.db"],
    expectedEvents: { "*": 0 },
  },
  {
    name: "backups delete unauthorized",
    method: "DELETE",
    url: "/api/backups/test1.zip",
    beforeTest: async (app) => {
      await createTestBackups(app);
    },
    afterTest: async (app) => {
      await ensureTestBackupFiles(app, 4);
    },
    expectedStatus: 401,
    expectedContent: ['"data":{}'],
    expectedEvents: { "*": 0 },
  },
  {
    name: "backups delete authorized as regular user",
    method: "DELETE",
    url: "/api/backups/test1.zip",
    headers: { Authorization: regularUserToken },
    beforeTest: async (app) => {
      await createTestBackups(app);
    },
    afterTest: async (app) => {
      await ensureTestBackupFiles(app, 4);
    },
    expectedStatus: 403,
    expectedContent: ['"data":{}'],
    expectedEvents: { "*": 0 },
  },
  {
    name: "backups delete authorized as superuser (missing file)",
    method: "DELETE",
    url: "/api/backups/missing.zip",
    headers: { Authorization: superuserToken },
    beforeTest: async (app) => {
      await createTestBackups(app);
    },
    afterTest: async (app) => {
      await ensureTestBackupFiles(app, 4);
    },
    expectedStatus: 400,
    expectedContent: ['"data":{}'],
    expectedEvents: { "*": 0 },
  },
  {
    name: "backups delete authorized as superuser (matching active backup)",
    method: "DELETE",
    url: "/api/backups/test1.zip",
    headers: { Authorization: superuserToken },
    beforeTest: async (app) => {
      await createTestBackups(app);
      app.store().set("@activeBackup", "test1.zip");
    },
    afterTest: async (app) => {
      await ensureTestBackupFiles(app, 4);
    },
    expectedStatus: 400,
    expectedContent: ['"data":{}'],
    expectedEvents: { "*": 0 },
  },
  {
    name: "backups delete authorized as superuser (existing file)",
    method: "DELETE",
    url: "/api/backups/test1.zip",
    headers: { Authorization: superuserToken },
    beforeTest: async (app) => {
      await createTestBackups(app);
      app.store().set("@activeBackup", "new.zip");
    },
    afterTest: async (app) => {
      const files = await getBackupFiles(app);
      if (files.length !== 3) {
        throw new Error(`Expected 3 backup files, got ${files.length}`);
      }
      if (files.some((file) => file.Key === "test1.zip")) {
        throw new Error("Expected backup test1.zip to be deleted");
      }
    },
    expectedStatus: 204,
    expectedEvents: { "*": 0 },
  },
  {
    name: "backups delete authorized as superuser (escaped name)",
    method: "DELETE",
    url: "/api/backups/%40test4.zip",
    headers: { Authorization: superuserToken },
    beforeTest: async (app) => {
      await createTestBackups(app);
    },
    afterTest: async (app) => {
      const files = await getBackupFiles(app);
      if (files.length !== 3) {
        throw new Error(`Expected 3 backup files, got ${files.length}`);
      }
      if (files.some((file) => file.Key === "@test4.zip")) {
        throw new Error("Expected backup @test4.zip to be deleted");
      }
    },
    expectedStatus: 204,
    expectedEvents: { "*": 0 },
  },
  {
    name: "backups restore unauthorized",
    method: "POST",
    url: "/api/backups/test1.zip/restore",
    beforeTest: async (app) => {
      await createTestBackups(app);
    },
    expectedStatus: 401,
    expectedContent: ['"data":{}'],
    expectedEvents: { "*": 0 },
  },
  {
    name: "backups restore authorized as regular user",
    method: "POST",
    url: "/api/backups/test1.zip/restore",
    headers: { Authorization: regularUserToken },
    beforeTest: async (app) => {
      await createTestBackups(app);
    },
    expectedStatus: 403,
    expectedContent: ['"data":{}'],
    expectedEvents: { "*": 0 },
  },
  {
    name: "backups restore authorized as superuser (missing file)",
    method: "POST",
    url: "/api/backups/missing.zip/restore",
    headers: { Authorization: superuserToken },
    beforeTest: async (app) => {
      await createTestBackups(app);
    },
    expectedStatus: 400,
    expectedContent: ['"data":{}'],
    expectedEvents: { "*": 0 },
  },
  {
    name: "backups restore authorized as superuser (active backup process)",
    method: "POST",
    url: "/api/backups/test1.zip/restore",
    headers: { Authorization: superuserToken },
    beforeTest: async (app) => {
      await createTestBackups(app);
      app.store().set("@activeBackup", "");
    },
    expectedStatus: 400,
    expectedContent: ['"data":{}'],
    expectedEvents: { "*": 0 },
  },
];

describe("backup API", () => {
  for (const scenario of scenarios) {
    const name = scenario.name ?? `${scenario.method} ${scenario.url}`;
    it(name, async () => {
      await runApiScenario(scenario);
    });
  }
});

async function createTestBackups(app: TestApp): Promise<void> {
  const errors: Error[] = [];

  const err1 = await app.CreateBackup(null, "test1.zip");
  if (err1) errors.push(err1);
  const err2 = await app.CreateBackup(null, "test2.zip");
  if (err2) errors.push(err2);
  const err3 = await app.CreateBackup(null, "test3.zip");
  if (err3) errors.push(err3);
  const err4 = await app.CreateBackup(null, "@test4.zip");
  if (err4) errors.push(err4);

  if (errors.length > 0) {
    throw new AggregateError(errors, errors.map((err) => err.message).join("\n"));
  }
}

async function getBackupFiles(app: TestApp) {
  await using fsys = app.NewBackupsFilesystem();
  return await fsys.List("");
}

async function ensureTestBackupFiles(app: TestApp, expected: number): Promise<void> {
  const files = await getBackupFiles(app);
  if (files.length !== expected) {
    throw new Error(`Expected ${expected} backup(s), got ${files.length}`);
  }
}

async function ensureNoBackups(app: TestApp): Promise<void> {
  await using fsys = app.NewBackupsFilesystem();
  const files = await fsys.List("");
  if (files.length !== 0) {
    throw new Error(`Expected 0 backup files, got ${files.length}`);
  }
}

function buildMultipartBody(): { body: Uint8Array; contentType: string } {
  const boundary = "---------------------------pbtestboundary";
  const encoder = new TextEncoder();
  const zipBytes = new Uint8Array([0x50, 0x4b, 0x03, 0x04]);

  const header = `--${boundary}\r\nContent-Disposition: form-data; name="file"; filename="test"\r\nContent-Type: application/zip\r\n\r\n`;
  const footer = `\r\n--${boundary}--\r\n`;

  const headerBytes = encoder.encode(header);
  const footerBytes = encoder.encode(footer);

  const body = new Uint8Array(headerBytes.length + zipBytes.length + footerBytes.length);
  body.set(headerBytes, 0);
  body.set(zipBytes, headerBytes.length);
  body.set(footerBytes, headerBytes.length + zipBytes.length);

  return {
    body,
    contentType: `multipart/form-data; boundary=${boundary}`,
  };
}
