// Ported from pocketbase/core/base_backup.go
// Deviation: backup/restore file I/O uses async fs + async archive helpers to avoid blocking the event loop.
// Deviation: database files use SQLite VACUUM INTO snapshots so cluster writes cannot race live WAL files during archiving.
// Deviation: cluster mode delegates backup exclusion and worker recycling to the primary process.

import { mkdir, mkdtemp, open, rm, stat } from "node:fs/promises";
import { basename, join } from "node:path";
import { clusterEnabled } from "../internal/cluster/context.ts";
import { CreateAsyncWithFileOverrides, ExtractAsync } from "../tools/archive/index.ts";
import { NewFileFromPathAsync } from "../tools/filesystem/file.ts";
import { snakecase } from "../tools/inflector/inflector.ts";
import { MoveDirContentAsync } from "../tools/osutils/dir.ts";
import { pseudorandomString } from "../tools/security/random.ts";
import { newBackupsFilesystemAsync, type App } from "./app.ts";
import {
  LocalAutocertCacheDirName,
  LocalBackupsDirName,
  LocalClusterGuardFileName,
  LocalNotifyDirName,
  LocalTempDirName,
} from "./base_paths.ts";
import { BackupEvent } from "./events.ts";
import { StoreKeyActiveBackup } from "./store.ts";
import { sendSystemAlertToAllSuperusers } from "./system_alert.ts";

// @todo consider removing after backups refactoring
const lostFoundDirName = "lost+found";

// CreateBackup creates a new backup of the current app pb_data directory.
//
// If name is empty, it will be autogenerated.
// If backup with the same name exists, the new backup file will replace it.
//
// The backup is executed within a transaction, meaning that new writes
// will be temporary "blocked" until the backup file is generated.
// PocketBun instead writes coherent SQLite snapshots to temporary files before
// archiving, so ZIP generation no longer holds a transaction or blocks writes.
//
// To safely perform the backup, it is recommended to have free disk space
// for at least 3x the size of the pb_data directory.
//
// By default backups are stored in pb_data/backups
// (the backups directory itself is excluded from the generated backup).
//
// When using S3 storage for the uploaded collection files, you have to
// take care manually to backup those since they are not part of the pb_data.
//
// Backups can be stored on S3 if it is configured in app.Settings().Backups.
export async function CreateBackup(app: App, ctx: unknown, name: string): Promise<Error | null> {
  const leaseToken = await acquireBackupLease(app, name);
  if (!leaseToken) {
    return new Error("try again later - another backup/restore operation has already been started");
  }

  try {
    // default root dir entries to exclude from the backup generation
    const event = new BackupEvent(app, ctx, name, [
      LocalBackupsDirName,
      LocalTempDirName,
      LocalNotifyDirName,
      LocalAutocertCacheDirName,
      LocalClusterGuardFileName,
      lostFoundDirName,
    ]);

    return (await app.OnBackupCreate().Trigger(event, async (e) => {
      // generate a default name if missing
      if (!e.Name) {
        e.Name = generateBackupName(e.App, "pb_backup_");
      }

      // make sure that the special temp directory exists
      // note: it needs to be inside the current pb_data to avoid "cross-device link" errors
      const localTempDir = join(e.App.dataDir(), LocalTempDirName);
      await mkdir(localTempDir, { recursive: true });

      // archive pb_data in a temp directory, excluding backups, temp dirs, and live SQLite sidecars
      // ---
      const tempPath = join(localTempDir, `pb_backup_${pseudorandomString(6)}`);
      try {
        const snapshotDir = await mkdtemp(join(localTempDir, "pb_backup_snapshot_"));
        try {
          const snapshots = new Map<string, string>([
            ["data.db", join(snapshotDir, "data.db")],
            ["auxiliary.db", join(snapshotDir, "auxiliary.db")],
          ]);
          e.App.db().query("VACUUM INTO ?").run(snapshots.get("data.db")!);
          e.App.auxDb().query("VACUUM INTO ?").run(snapshots.get("auxiliary.db")!);
          await CreateAsyncWithFileOverrides(
            e.App.dataDir(),
            tempPath,
            snapshots,
            ...e.Exclude,
            "data.db-wal",
            "data.db-shm",
            "data.db-journal",
            "auxiliary.db-wal",
            "auxiliary.db-shm",
            "auxiliary.db-journal",
          );
        } finally {
          await rm(snapshotDir, { recursive: true, force: true });
        }
      } catch (error) {
        return error as Error;
      }

      // persist the backup in the backups filesystem
      // ---
      try {
        await using fsys = await newBackupsFilesystemAsync(e.App);
        fsys.SetContext(e.Context);
        const file = await NewFileFromPathAsync(tempPath);
        file.OriginalName = e.Name;
        file.Name = file.OriginalName;
        await fsys.UploadFile(file, file.Name);
      } catch (error) {
        return error as Error;
      } finally {
        await rm(tempPath, { force: true });
      }

      return null;
    })) as Error | null;
  } finally {
    await releaseBackupLease(app, leaseToken);
  }
}

// RestoreBackup restores the backup with the specified name and restarts
// the current running application process.
//
// NB! This feature is experimental and currently is expected to work only on UNIX based systems.
//
// To safely perform the restore it is recommended to have free disk space
// for at least 2x the size of the restored pb_data backup.
//
// The performed steps are:
//
//  1. Download the backup with the specified name in a temp location
//     (this is in case of S3; otherwise it creates a temp copy of the zip)
//
//  2. Extract the backup in a temp directory inside the app "pb_data"
//     (eg. "pb_data/.pb_temp_to_delete/pb_restore").
//
//  3. Move the current app "pb_data" content (excluding the local backups and the special temp dir)
//     under another temp sub dir that will be deleted on the next app start up
//     (eg. "pb_data/.pb_temp_to_delete/old_pb_data").
//     This is because on some environments it may not be allowed
//     to delete the currently open "pb_data" files.
//
//  4. Move the extracted dir content to the app "pb_data".
//
//  5. Restart the app (on successful app bootstap it will also remove the old pb_data).
//
// If a failure occure during the restore process the dir changes are reverted.
// If for whatever reason the revert is not possible, it panics.
//
// Note that if your pb_data has custom network mounts as subdirectories, then
// it is possible the restore to fail during the `os.Rename` operations
// (see https://github.com/pocketbase/pocketbase/issues/4647).
export async function RestoreBackup(app: App, ctx: unknown, name: string): Promise<Error | null> {
  const leaseToken = await acquireBackupLease(app, name);
  if (!leaseToken) {
    return new Error("try again later - another backup/restore operation has already been started");
  }

  let clusterQuiesced = false;
  try {
    // default root dir entries to exclude from the backup restore
    const event = new BackupEvent(app, ctx, name, [
      LocalBackupsDirName,
      LocalTempDirName,
      LocalNotifyDirName,
      LocalAutocertCacheDirName,
      LocalClusterGuardFileName,
      lostFoundDirName,
    ]);

    return (await app.OnBackupRestore().Trigger(event, async (e) => {
      if (process.platform === "win32") {
        return new Error("restore is not supported on Windows");
      }

      // make sure that the special temp directory exists
      // note: it needs to be inside the current pb_data to avoid "cross-device link" errors
      const localTempDir = join(e.App.dataDir(), LocalTempDirName);
      await mkdir(localTempDir, { recursive: true });

      try {
        await using fsys = await newBackupsFilesystemAsync(e.App);
        fsys.SetContext(e.Context);
        if (!(await fsys.Exists(name))) {
          return new Error(`missing or invalid backup file ${JSON.stringify(name)} to restore`);
        }

        const extractedDataDir = join(localTempDir, `pb_restore_${pseudorandomString(8)}`);
        try {
          // extract the zip
          if (e.App.settings().backups.s3.enabled) {
            using reader =
              typeof fsys.GetReaderAsync === "function" ? await fsys.GetReaderAsync(name) : await fsys.GetReader(name);
            const tempZipPath = join(localTempDir, `pb_restore_zip_${pseudorandomString(6)}`);
            try {
              // create a temp zip file from the blob reader and try to extract it
              await writeReaderToFile(tempZipPath, reader);
              await ExtractAsync(tempZipPath, extractedDataDir);
            } finally {
              try {
                // remove the temp zip file since we no longer need it
                // (this is in case the app restarts and the defer calls are not called)
                await rm(tempZipPath, { force: true });
              } catch (error) {
                e.App.Logger().Warn(
                  "[RestoreBackup] Failed to remove the temp zip backup file",
                  "file",
                  tempZipPath,
                  "error",
                  String(error),
                );
              }
            }
          } else {
            // manually construct the local path to avoid creating a copy of the zip file
            // since the blob reader currently doesn't implement ReaderAt
            const zipPath = join(e.App.dataDir(), LocalBackupsDirName, basename(name));
            await ExtractAsync(zipPath, extractedDataDir);
          }

          // ensure that at least a database file exists
          try {
            await stat(join(extractedDataDir, "data.db"));
          } catch (error) {
            return new Error(`data.db file is missing or invalid: ${(error as Error).message}`);
          }

          if (clusterEnabled()) {
            const { beginClusterRestore } = await import("../internal/cluster/worker.ts");
            try {
              await beginClusterRestore(leaseToken);
              clusterQuiesced = true;
            } catch (error) {
              return error instanceof Error ? error : new Error(String(error));
            }
          }

          const oldTempDataDir = join(localTempDir, `old_pb_data_${pseudorandomString(8)}`);

          const replaceErr = await e.App.RunInTransaction((txApp) => {
            return txApp.AuxRunInTransaction(async (auxApp) => {
              // move the current pb_data content to a special temp location
              // that will hold the old data between dirs replace
              // (the temp dir will be automatically removed on the next app start)
              try {
                await MoveDirContentAsync(auxApp.dataDir(), oldTempDataDir, ...e.Exclude);
              } catch (error) {
                return new Error(`failed to move the current pb_data content to a temp location: ${(error as Error).message}`);
              }

              // move the extracted archive content to the app's pb_data
              try {
                await MoveDirContentAsync(extractedDataDir, auxApp.dataDir(), ...e.Exclude);
              } catch (error) {
                return new Error(`failed to move the extracted archive content to pb_data: ${(error as Error).message}`);
              }

              return null;
            });
          });

          if (replaceErr) {
            return replaceErr;
          }

          const revertDataDirChanges = async (): Promise<Error | null> => {
            return e.App.RunInTransaction((txApp) => {
              return txApp.AuxRunInTransaction(async (auxApp) => {
                try {
                  await MoveDirContentAsync(auxApp.dataDir(), extractedDataDir, ...e.Exclude);
                } catch (error) {
                  return new Error(`failed to revert the extracted dir change: ${(error as Error).message}`);
                }

                try {
                  await MoveDirContentAsync(oldTempDataDir, auxApp.dataDir(), ...e.Exclude);
                } catch (error) {
                  return new Error(`failed to revert old pb_data dir change: ${(error as Error).message}`);
                }

                return null;
              });
            });
          };

          // restart the app
          let restartErr: Error | null = null;
          if (clusterEnabled()) {
            try {
              const { completeClusterRestore } = await import("../internal/cluster/worker.ts");
              await completeClusterRestore(leaseToken);
              clusterQuiesced = false;
            } catch (error) {
              restartErr = error instanceof Error ? error : new Error(String(error));
            }
          } else {
            restartErr = typeof e.App.RestartAsync === "function" ? await e.App.RestartAsync() : e.App.Restart();
          }
          if (restartErr) {
            const revertErr = await revertDataDirChanges();
            if (revertErr) {
              if (clusterEnabled()) {
                const { abortClusterRestore } = await import("../internal/cluster/worker.ts");
                await abortClusterRestore(leaseToken, true, revertErr.message).catch(() => {});
                clusterQuiesced = false;
              }
              throw revertErr;
            }

            return new Error(`failed to restart the app process: ${restartErr.message}`);
          }
        } finally {
          await rm(extractedDataDir, { recursive: true, force: true });
        }
      } catch (error) {
        return error as Error;
      }

      return null;
    })) as Error | null;
  } finally {
    if (clusterQuiesced) {
      const { abortClusterRestore } = await import("../internal/cluster/worker.ts");
      await abortClusterRestore(leaseToken, false, "restore did not complete").catch((error) => {
        app.Logger().Error("Failed to resume cluster after restore error", "error", error);
      });
    }
    await releaseBackupLease(app, leaseToken).catch((error) => {
      app.Logger().Error("Failed to release backup operation", "error", error);
    });
  }
}

async function acquireBackupLease(app: App, name: string): Promise<string | null> {
  if (clusterEnabled()) {
    const { acquireClusterBackupLease } = await import("../internal/cluster/worker.ts");
    return acquireClusterBackupLease(name);
  }
  if (app.store().has(StoreKeyActiveBackup)) {
    return null;
  }
  app.store().set(StoreKeyActiveBackup, name);
  return "local";
}

async function releaseBackupLease(app: App, leaseToken: string): Promise<void> {
  if (clusterEnabled()) {
    const { releaseClusterBackupLease } = await import("../internal/cluster/worker.ts");
    await releaseClusterBackupLease(leaseToken);
    return;
  }
  app.store().remove(StoreKeyActiveBackup);
}

// registerAutobackupHooks registers the autobackup app serve hooks.
export function registerAutobackupHooks(app: App): void {
  const jobId = "__pbAutoBackup__";

  const loadJob = () => {
    const rawSchedule = app.settings().backups.cron;
    if (!rawSchedule) {
      app.Cron().Remove(jobId);
      return;
    }

    app.Cron().Add(jobId, rawSchedule, () => {
      void (async () => {
        const autoPrefix = "@auto_pb_backup_";
        const name = generateBackupName(app, autoPrefix);

        const backupErr = await app.CreateBackup(null, name);
        if (backupErr) {
          app.Logger().Error("[Backup cron] Failed to create backup", "name", name, "error", backupErr.message);

          const alertError = await sendSystemAlertToAllSuperusers(
            app,
            "Autobackup failure",
            `Failed to create/upload automated backup. Raw error:\n${backupErr.message}`,
          );
          if (alertError) {
            app.Logger().Warn("[Backup cron] Failed to send backup error alerts", "name", name, "error", alertError.message);
          }
        }

        const maxKeep = app.settings().backups.cronMaxKeep;
        if (maxKeep === 0) {
          return; // no explicit limit
        }

        let fsys: ReturnType<App["NewBackupsFilesystem"]>;
        try {
          fsys = await newBackupsFilesystemAsync(app);
        } catch (error) {
          app.Logger().Error("[Backup cron] Failed to initialize the backup filesystem", "error", String(error));
          return;
        }

        await using managedFsys = fsys;
        try {
          const files = await managedFsys.List(autoPrefix);
          if (maxKeep >= files.length) {
            return; // nothing to remove
          }

          // sort desc
          files.sort((a, b) => b.ModTime.getTime() - a.ModTime.getTime());
          // keep only the most recent n auto backup files
          const toRemove = files.slice(maxKeep);

          for (const file of toRemove) {
            try {
              await managedFsys.Delete(file.Key);
            } catch (error) {
              app
                .Logger()
                .Error("[Backup cron] Failed to remove old autogenerated backup", "key", file.Key, "error", String(error));
            }
          }
        } catch (error) {
          app.Logger().Error("[Backup cron] Failed to list autogenerated backups", "error", String(error));
        }
      })().catch((error) => {
        app.Logger().Error("[Backup cron] Failed to run backup task", "error", String(error));
      });
    });
  };

  app.OnBootstrap().BindFunc((event) => {
    const result = event.Next();
    loadJob();
    return result;
  });

  app.OnSettingsReload().BindFunc((event) => {
    const result = event.Next();
    loadJob();
    return result;
  });
}

function generateBackupName(app: App, prefix: string): string {
  let appName = snakecase(app.settings().meta.appName);
  if (appName.length > 50) {
    appName = appName.slice(0, 50);
  }

  const now = new Date();
  const stamp = [
    now.getUTCFullYear(),
    pad2(now.getUTCMonth() + 1),
    pad2(now.getUTCDate()),
    pad2(now.getUTCHours()),
    pad2(now.getUTCMinutes()),
    pad2(now.getUTCSeconds()),
  ].join("");

  return `${prefix}${appName}_${stamp}.zip`;
}

function pad2(value: number): string {
  return value < 10 ? `0${value}` : String(value);
}

type ReadableBackupSource = {
  read: (size?: number) => Uint8Array | null | Promise<Uint8Array | null>;
  close: () => void;
};

async function writeReaderToFile(path: string, reader: ReadableBackupSource): Promise<void> {
  await using out = await open(path, "w");
  for (;;) {
    const chunk = await Promise.resolve(reader.read(64 * 1024));
    if (!chunk || chunk.length === 0) {
      break;
    }

    let offset = 0;
    while (offset < chunk.length) {
      const result = await out.write(chunk, offset, chunk.length - offset, null);
      const bytesWritten = result.bytesWritten ?? 0;
      if (bytesWritten <= 0) {
        throw new Error("failed writing backup chunk");
      }
      offset += bytesWritten;
    }
  }
}
