// Ported from pocketbase/core/collection_model.go

import type { App } from "./app.ts";
import { toBoolValue, toNumberValue, toStringValue } from "../internal/compat/cast.ts";
import { parseIndex, findSingleColumnUniqueIndex } from "../tools/dbutils/index.ts";
import { toUniqueStringSlice } from "../tools/list/list.ts";
import { pseudorandomStringWithAlphabet } from "../tools/security/random.ts";
import { JSONRaw, ParseDateTime, DateTime } from "../tools/types/index.ts";
import {
  AuthAlertConfig,
  EmailTemplate,
  MFAConfig,
  OAuth2Config,
  OTPConfig,
  PasswordAuthConfig,
  TokenConfigValue,
  createDefaultAuthOptions,
  normalizeOAuth2ProviderConfig,
  type CollectionAuthOptions,
} from "./collection_model_auth_options.ts";
import { DefaultIdAlphabet } from "./db.ts";
import {
  FieldNameEmail,
  FieldNameEmailVisibility,
  FieldNameId,
  FieldNamePassword,
  FieldNameTokenKey,
  FieldNameVerified,
} from "./field.ts";
import { BoolField } from "./field_bool.ts";
import { EmailField } from "./field_email.ts";
import { PasswordField } from "./field_password.ts";
import { TextField, defaultLowercaseRecordIdPattern } from "./field_text.ts";
import { FieldsList, NewFieldsList } from "./fields_list.ts";

export const CollectionNameSuperusers = "_superusers";
export const CollectionTypeBase = "base";
export const CollectionTypeAuth = "auth";
export const CollectionTypeView = "view";

export type CollectionField = {
  name: string;
  type: string;
  system: boolean;
  hidden: boolean;
  raw: Record<string, unknown>;
};

export type CollectionRow = {
  id: string;
  name: string;
  system: number | boolean;
  type: string;
  fields: string;
  indexes: string;
  listRule: string | null;
  viewRule: string | null;
  createRule: string | null;
  updateRule: string | null;
  deleteRule: string | null;
  options: string;
  created?: string;
  updated?: string;
};

export type CollectionInit = {
  id?: string;
  name?: string;
  type?: string;
  system?: boolean;
  fields?: CollectionField[];
  Fields?: FieldsList;
  indexes?: string[];
  listRule?: string | null;
  viewRule?: string | null;
  createRule?: string | null;
  updateRule?: string | null;
  deleteRule?: string | null;
  options?: Record<string, unknown> | null;
  created?: DateTime | string | null;
  updated?: DateTime | string | null;
};

export class Collection {
  id = "";
  name = "";
  type = "";
  system = false;
  fields: CollectionField[] = [];
  Fields: FieldsList = new FieldsList();
  // @todo consider changing the indexes field to a "getter" for the sqlite_master table?
  indexes: string[] = [];
  listRule: string | null = null;
  viewRule: string | null = null;
  createRule: string | null = null;
  updateRule: string | null = null;
  deleteRule: string | null = null;
  created: DateTime = new DateTime();
  updated: DateTime = new DateTime();
  RawOptions: JSONRaw = new JSONRaw();

  // auth options
  AuthRule: string | null = null;
  ManageRule: string | null = null;
  AuthAlert: AuthAlertConfig = new AuthAlertConfig();
  OAuth2: OAuth2Config = new OAuth2Config();
  PasswordAuth: PasswordAuthConfig = new PasswordAuthConfig();
  MFA: MFAConfig = new MFAConfig();
  OTP: OTPConfig = new OTPConfig();
  AuthToken: TokenConfigValue = new TokenConfigValue();
  PasswordResetToken: TokenConfigValue = new TokenConfigValue();
  EmailChangeToken: TokenConfigValue = new TokenConfigValue();
  VerificationToken: TokenConfigValue = new TokenConfigValue();
  FileToken: TokenConfigValue = new TokenConfigValue();
  VerificationTemplate: EmailTemplate = new EmailTemplate();
  ResetPasswordTemplate: EmailTemplate = new EmailTemplate();
  ConfirmEmailChangeTemplate: EmailTemplate = new EmailTemplate();

  // view options
  ViewQuery = "";

  #isNew = true;
  #disableIntegrityChecks = false;
  #autogeneratedId = "";
  #lastSavedId = "";

  constructor(values: CollectionInit = {}) {
    this.id = values.id ?? "";
    this.name = values.name ?? "";
    this.type = values.type ?? this.type;
    this.system = Boolean(values.system);
    this.fields = values.fields ?? [];
    this.Fields = values.Fields ?? new FieldsList();
    this.indexes = values.indexes ?? [];
    this.listRule = values.listRule ?? null;
    this.viewRule = values.viewRule ?? null;
    this.createRule = values.createRule ?? null;
    this.updateRule = values.updateRule ?? null;
    this.deleteRule = values.deleteRule ?? null;
    if (values.created) {
      this.created = values.created instanceof DateTime ? values.created : ParseDateTime(values.created);
    }
    if (values.updated) {
      this.updated = values.updated instanceof DateTime ? values.updated : ParseDateTime(values.updated);
    }

    if (values.options) {
      this.options = values.options;
    }
  }

  get Id(): string {
    return this.id;
  }

  set Id(value: string) {
    this.id = value;
  }

  get Name(): string {
    return this.name;
  }

  set Name(value: string) {
    this.name = value;
  }

  get Type(): string {
    return this.type;
  }

  set Type(value: string) {
    this.type = value;
  }

  get System(): boolean {
    return this.system;
  }

  set System(value: boolean) {
    this.system = Boolean(value);
  }

  get ListRule(): string | null {
    return this.listRule;
  }

  set ListRule(value: string | null) {
    this.listRule = value ?? null;
  }

  get ViewRule(): string | null {
    return this.viewRule;
  }

  set ViewRule(value: string | null) {
    this.viewRule = value ?? null;
  }

  get CreateRule(): string | null {
    return this.createRule;
  }

  set CreateRule(value: string | null) {
    this.createRule = value ?? null;
  }

  get UpdateRule(): string | null {
    return this.updateRule;
  }

  set UpdateRule(value: string | null) {
    this.updateRule = value ?? null;
  }

  get DeleteRule(): string | null {
    return this.deleteRule;
  }

  set DeleteRule(value: string | null) {
    this.deleteRule = value ?? null;
  }

  get Created(): DateTime {
    return this.created;
  }

  set Created(value: DateTime) {
    this.created = value;
  }

  get Updated(): DateTime {
    return this.updated;
  }

  set Updated(value: DateTime) {
    this.updated = value;
  }

  get options(): Record<string, unknown> {
    return this.rawOptions();
  }

  set options(value: Record<string, unknown> | null) {
    if (!value || typeof value !== "object") {
      return;
    }
    this.applyOptions(value);
  }

  SafeOptions(): Record<string, unknown> {
    if (this.IsView()) {
      return { viewQuery: this.ViewQuery };
    }
    if (this.IsAuth()) {
      return this.safeAuthOptions();
    }
    return {};
  }

  TableName(): string {
    return "_collections";
  }

  BaseFilesPath(): string {
    return this.id;
  }

  IsBase(): boolean {
    return this.type === CollectionTypeBase;
  }

  IsAuth(): boolean {
    return this.type === CollectionTypeAuth;
  }

  IsView(): boolean {
    return this.type === CollectionTypeView;
  }

  isAuth(): boolean {
    return this.IsAuth();
  }

  isView(): boolean {
    return this.IsView();
  }

  isNew(): boolean {
    return this.#isNew;
  }

  IsNew(): boolean {
    return this.#isNew;
  }

  markNew(value = true): void {
    this.#isNew = value;
    this.#lastSavedId = value ? "" : this.id;
  }

  LastSavedPK(): string {
    return this.#lastSavedId;
  }

  PK(): string {
    return this.id;
  }

  MarkAsNew(): void {
    this.markNew(true);
  }

  MarkAsNotNew(): void {
    this.markNew(false);
  }

  IntegrityChecks(enable: boolean): void {
    this.#disableIntegrityChecks = !enable;
  }

  integrityChecksEnabled(): boolean {
    return !this.#disableIntegrityChecks;
  }

  PostScan(): Error | null {
    this.markNew(false);
    return this.unmarshalRawOptions();
  }

  unmarshalRawOptions(): Error | null {
    let raw: unknown = null;
    try {
      raw = this.RawOptions.toJSON();
    } catch {
      raw = null;
    }

    if (!raw || typeof raw !== "object") {
      return null;
    }

    if (this.IsView()) {
      const record = raw as Record<string, unknown>;
      this.ViewQuery = toStringValue(record.viewQuery ?? record.ViewQuery);
    } else if (this.IsAuth()) {
      this.applyOptions(raw as Record<string, unknown>);
    }

    return null;
  }

  UnmarshalJSON(raw: string | Record<string, unknown>): Error | null {
    const data = typeof raw === "string" ? (JSON.parse(raw) as Record<string, unknown>) : raw;
    if (this.IsNew() && this.type === "") {
      const minimalType = toStringValue(data.type);
      const minimalName = toStringValue(data.name);
      const minimalId = toStringValue(data.id);
      const blank = NewCollection(minimalType, minimalName, minimalId);
      this.copyFrom(blank);
    }
    applyCollectionData(this, data);
    return null;
  }

  MarshalJSON(): string {
    return JSON.stringify(this);
  }

  toJSON(): Record<string, unknown> {
    const base = this.baseJSON();

    if (this.IsView()) {
      return {
        ...base,
        viewQuery: this.ViewQuery,
      };
    }

    if (this.IsAuth()) {
      const options = this.safeAuthOptions();
      return {
        ...base,
        authRule: options.authRule,
        manageRule: options.manageRule,
        authAlert: options.authAlert,
        oauth2: options.oauth2,
        passwordAuth: options.passwordAuth,
        mfa: options.mfa,
        otp: options.otp,
        authToken: options.authToken,
        passwordResetToken: options.passwordResetToken,
        emailChangeToken: options.emailChangeToken,
        verificationToken: options.verificationToken,
        fileToken: options.fileToken,
        verificationTemplate: options.verificationTemplate,
        resetPasswordTemplate: options.resetPasswordTemplate,
        confirmEmailChangeTemplate: options.confirmEmailChangeTemplate,
      };
    }

    return base;
  }

  String(): string {
    return JSON.stringify(this);
  }

  DBExport(): Record<string, unknown> {
    const result: Record<string, unknown> = {
      createRule: this.createRule,
      created: this.created,
      deleteRule: this.deleteRule,
      fields: this.Fields,
      id: this.id,
      indexes: this.indexes,
      listRule: this.listRule,
      name: this.name,
      options: "{}",
      system: this.system,
      type: this.type,
      updateRule: this.updateRule,
      updated: this.updated,
      viewRule: this.viewRule,
    };

    if (this.IsView()) {
      result.options = { viewQuery: this.ViewQuery };
    } else if (this.IsAuth()) {
      result.options = this.rawAuthOptions();
    }

    return result;
  }

  GetIndex(name: string): string {
    for (const idx of this.indexes) {
      if (parseIndex(idx).indexName.toLowerCase() === name.toLowerCase()) {
        return idx;
      }
    }
    return "";
  }

  AddIndex(name: string, unique: boolean, columnsExpr: string, optWhereExpr: string): void {
    this.RemoveIndex(name);

    let sql = "CREATE ";
    if (unique) {
      sql += "UNIQUE ";
    }
    sql += `INDEX \`${name}\` ON \`${this.name}\` (${columnsExpr})`;
    if (optWhereExpr) {
      sql += ` WHERE ${optWhereExpr}`;
    }

    this.indexes = [...this.indexes, sql];
  }

  RemoveIndex(name: string): void {
    for (let i = 0; i < this.indexes.length; i += 1) {
      const idx = this.indexes[i] ?? "";
      if (parseIndex(idx).indexName.toLowerCase() === name.toLowerCase()) {
        this.indexes.splice(i, 1);
        return;
      }
    }
  }

  idChecksum(): string {
    return `pbc_${crc32Checksum(this.type + this.name)}`;
  }

  initDefaultId(): void {
    if (this.id === "") {
      this.id = this.idChecksum();
      this.#autogeneratedId = this.id;
    }
  }

  updateGeneratedIdIfExists(app: App): void {
    if (!this.IsNew() || this.id === "" || this.id !== this.#autogeneratedId) {
      return;
    }

    let newId = this.idChecksum();

    for (let i = 2; i < 1000; i += 1) {
      const exists = app.db().query("select id from _collections where id = ? limit 1").get(newId) as
        | { id?: string }
        | undefined;
      if (!exists?.id) {
        break;
      }
      newId = this.idChecksum() + String(i);
    }

    if (this.id === newId) {
      return;
    }

    for (let i = 0; i < this.indexes.length; i += 1) {
      const parsed = parseIndex(this.indexes[i] ?? "");
      const original = parsed.indexName;
      parsed.indexName = parsed.indexName.replaceAll(this.id, newId);
      if (parsed.indexName !== original) {
        this.indexes[i] = parsed.build();
      }
    }

    this.id = newId;
  }

  setDefaultAuthOptions(): void {
    const defaults = createDefaultAuthOptions();
    this.applyAuthOptions(defaults);
  }

  unsetMissingOAuth2MappedFields(): void {
    if (!this.IsAuth()) {
      return;
    }

    const fields = this.Fields;

    if (this.OAuth2.MappedFields.Id && !fields.GetByName(this.OAuth2.MappedFields.Id)) {
      this.OAuth2.MappedFields.Id = "";
    }
    if (this.OAuth2.MappedFields.Name && !fields.GetByName(this.OAuth2.MappedFields.Name)) {
      this.OAuth2.MappedFields.Name = "";
    }
    if (this.OAuth2.MappedFields.Username && !fields.GetByName(this.OAuth2.MappedFields.Username)) {
      this.OAuth2.MappedFields.Username = "";
    }
    if (this.OAuth2.MappedFields.AvatarURL && !fields.GetByName(this.OAuth2.MappedFields.AvatarURL)) {
      this.OAuth2.MappedFields.AvatarURL = "";
    }
  }

  initDefaultFields(): void {
    switch (this.type) {
      case CollectionTypeBase:
        this.initIdField();
        break;
      case CollectionTypeAuth:
        this.initIdField();
        this.initPasswordField();
        this.initTokenKeyField();
        this.initEmailField();
        this.initEmailVisibilityField();
        this.initVerifiedField();
        break;
      case CollectionTypeView:
        break;
      default:
        this.initIdField();
        break;
    }

    this.fields = parseCollectionFields(this.Fields.toJSON());
  }

  initIdField(): void {
    const existing = this.Fields.GetByName(FieldNameId) as TextField | null;
    if (!existing) {
      const field = new TextField();
      field.Name = FieldNameId;
      field.System = true;
      field.PrimaryKey = true;
      field.Required = true;
      field.Min = 15;
      field.Max = 15;
      field.Pattern = defaultLowercaseRecordIdPattern;
      field.AutogeneratePattern = "[a-z0-9]{15}";
      this.Fields = NewFieldsList(field, ...this.Fields);
    } else {
      existing.System = true;
      existing.Required = true;
      existing.PrimaryKey = true;
      existing.Hidden = false;
      if (!existing.Pattern) {
        existing.Pattern = defaultLowercaseRecordIdPattern;
      }
    }
  }

  initPasswordField(): void {
    const existing = this.Fields.GetByName(FieldNamePassword) as PasswordField | null;
    if (!existing) {
      const field = new PasswordField();
      field.Name = FieldNamePassword;
      field.System = true;
      field.Hidden = true;
      field.Required = true;
      field.Min = 8;
      this.Fields.Add(field);
    } else {
      existing.System = true;
      existing.Hidden = true;
      existing.Required = true;
    }
  }

  initTokenKeyField(): void {
    const existing = this.Fields.GetByName(FieldNameTokenKey) as TextField | null;
    if (!existing) {
      const field = new TextField();
      field.Name = FieldNameTokenKey;
      field.System = true;
      field.Hidden = true;
      field.Min = 30;
      field.Max = 60;
      field.Required = true;
      field.AutogeneratePattern = "[a-zA-Z0-9]{50}";
      this.Fields.Add(field);
    } else {
      existing.System = true;
      existing.Hidden = true;
      existing.Required = true;
    }

    if (!findSingleColumnUniqueIndex(this.indexes, FieldNameTokenKey)[1]) {
      this.indexes = [
        ...this.indexes,
        `CREATE UNIQUE INDEX \`${this.fieldIndexName(FieldNameTokenKey)}\` ON \`${this.name}\` (\`${FieldNameTokenKey}\`)`,
      ];
    }
  }

  initEmailField(): void {
    const existing = this.Fields.GetByName(FieldNameEmail) as EmailField | null;
    if (!existing) {
      const field = new EmailField();
      field.Name = FieldNameEmail;
      field.System = true;
      field.Required = true;
      this.Fields.Add(field);
    } else {
      existing.System = true;
      existing.Hidden = false;
    }

    if (!findSingleColumnUniqueIndex(this.indexes, FieldNameEmail)[1]) {
      this.indexes = [
        ...this.indexes,
        `CREATE UNIQUE INDEX \`${this.fieldIndexName(FieldNameEmail)}\` ON \`${this.name}\` (\`${FieldNameEmail}\`) WHERE \`${FieldNameEmail}\` != ''`,
      ];
    }
  }

  initEmailVisibilityField(): void {
    const existing = this.Fields.GetByName(FieldNameEmailVisibility) as BoolField | null;
    if (!existing) {
      const field = new BoolField();
      field.Name = FieldNameEmailVisibility;
      field.System = true;
      this.Fields.Add(field);
    } else {
      existing.System = true;
    }
  }

  initVerifiedField(): void {
    const existing = this.Fields.GetByName(FieldNameVerified) as BoolField | null;
    if (!existing) {
      const field = new BoolField();
      field.Name = FieldNameVerified;
      field.System = true;
      this.Fields.Add(field);
    } else {
      existing.System = true;
    }
  }

  fieldIndexName(field: string): string {
    let name = `idx_${field}_`;

    if (this.id) {
      name += this.id;
    } else if (this.name) {
      name += this.name;
    } else {
      name += pseudorandomStringWithAlphabet(10, DefaultIdAlphabet);
    }

    return name.length > 64 ? name.slice(0, 64) : name;
  }

  private baseJSON(): Record<string, unknown> {
    return {
      id: this.id,
      name: this.name,
      type: this.type,
      system: this.system,
      fields: this.Fields,
      indexes: this.indexes,
      listRule: this.listRule,
      viewRule: this.viewRule,
      createRule: this.createRule,
      updateRule: this.updateRule,
      deleteRule: this.deleteRule,
      created: this.created,
      updated: this.updated,
    };
  }

  private copyFrom(other: Collection): void {
    this.id = other.id;
    this.name = other.name;
    this.type = other.type;
    this.system = other.system;
    this.fields = [...other.fields];
    this.Fields = other.Fields.Clone();
    this.indexes = [...other.indexes];
    this.listRule = other.listRule;
    this.viewRule = other.viewRule;
    this.createRule = other.createRule;
    this.updateRule = other.updateRule;
    this.deleteRule = other.deleteRule;
    this.created = other.created;
    this.updated = other.updated;
    this.RawOptions = other.RawOptions;
    this.ViewQuery = other.ViewQuery;
    this.AuthRule = other.AuthRule;
    this.ManageRule = other.ManageRule;
    this.AuthAlert = other.AuthAlert;
    this.OAuth2 = other.OAuth2;
    this.PasswordAuth = other.PasswordAuth;
    this.MFA = other.MFA;
    this.OTP = other.OTP;
    this.AuthToken = other.AuthToken;
    this.PasswordResetToken = other.PasswordResetToken;
    this.EmailChangeToken = other.EmailChangeToken;
    this.VerificationToken = other.VerificationToken;
    this.FileToken = other.FileToken;
    this.VerificationTemplate = other.VerificationTemplate;
    this.ResetPasswordTemplate = other.ResetPasswordTemplate;
    this.ConfirmEmailChangeTemplate = other.ConfirmEmailChangeTemplate;
    this.#isNew = other.#isNew;
    this.#disableIntegrityChecks = other.#disableIntegrityChecks;
    this.#autogeneratedId = other.#autogeneratedId;
  }

  private applyOptions(raw: Record<string, unknown>): void {
    if (this.IsView()) {
      if (Object.prototype.hasOwnProperty.call(raw, "viewQuery")) {
        this.ViewQuery = toStringValue(raw.viewQuery);
      }
      if (Object.prototype.hasOwnProperty.call(raw, "ViewQuery")) {
        this.ViewQuery = toStringValue(raw.ViewQuery);
      }
      return;
    }

    if (!this.IsAuth()) {
      return;
    }

    if (Object.prototype.hasOwnProperty.call(raw, "authRule")) {
      this.AuthRule = raw.authRule === null ? null : toStringValue(raw.authRule);
    } else if (Object.prototype.hasOwnProperty.call(raw, "AuthRule")) {
      this.AuthRule = raw.AuthRule === null ? null : toStringValue(raw.AuthRule);
    }

    if (Object.prototype.hasOwnProperty.call(raw, "manageRule")) {
      this.ManageRule = raw.manageRule === null ? null : toStringValue(raw.manageRule);
    } else if (Object.prototype.hasOwnProperty.call(raw, "ManageRule")) {
      this.ManageRule = raw.ManageRule === null ? null : toStringValue(raw.ManageRule);
    }

    if (Object.prototype.hasOwnProperty.call(raw, "authAlert") || Object.prototype.hasOwnProperty.call(raw, "AuthAlert")) {
      this.AuthAlert = mergeAuthAlertConfig(this.AuthAlert, raw.authAlert ?? raw.AuthAlert);
    }
    if (Object.prototype.hasOwnProperty.call(raw, "oauth2") || Object.prototype.hasOwnProperty.call(raw, "OAuth2")) {
      this.OAuth2 = mergeOAuth2Config(this.OAuth2, raw.oauth2 ?? raw.OAuth2);
    }
    if (
      Object.prototype.hasOwnProperty.call(raw, "passwordAuth") ||
      Object.prototype.hasOwnProperty.call(raw, "PasswordAuth")
    ) {
      this.PasswordAuth = mergePasswordAuthConfig(this.PasswordAuth, raw.passwordAuth ?? raw.PasswordAuth);
    }
    if (Object.prototype.hasOwnProperty.call(raw, "mfa") || Object.prototype.hasOwnProperty.call(raw, "MFA")) {
      this.MFA = mergeMFAConfig(this.MFA, raw.mfa ?? raw.MFA);
    }
    if (Object.prototype.hasOwnProperty.call(raw, "otp") || Object.prototype.hasOwnProperty.call(raw, "OTP")) {
      this.OTP = mergeOTPConfig(this.OTP, raw.otp ?? raw.OTP);
    }

    if (Object.prototype.hasOwnProperty.call(raw, "authToken") || Object.prototype.hasOwnProperty.call(raw, "AuthToken")) {
      this.AuthToken = mergeTokenConfigFromRaw(this.AuthToken, raw.authToken ?? raw.AuthToken);
    }
    if (
      Object.prototype.hasOwnProperty.call(raw, "passwordResetToken") ||
      Object.prototype.hasOwnProperty.call(raw, "PasswordResetToken")
    ) {
      this.PasswordResetToken = mergeTokenConfigFromRaw(
        this.PasswordResetToken,
        raw.passwordResetToken ?? raw.PasswordResetToken,
      );
    }
    if (
      Object.prototype.hasOwnProperty.call(raw, "emailChangeToken") ||
      Object.prototype.hasOwnProperty.call(raw, "EmailChangeToken")
    ) {
      this.EmailChangeToken = mergeTokenConfigFromRaw(this.EmailChangeToken, raw.emailChangeToken ?? raw.EmailChangeToken);
    }
    if (
      Object.prototype.hasOwnProperty.call(raw, "verificationToken") ||
      Object.prototype.hasOwnProperty.call(raw, "VerificationToken")
    ) {
      this.VerificationToken = mergeTokenConfigFromRaw(this.VerificationToken, raw.verificationToken ?? raw.VerificationToken);
    }
    if (Object.prototype.hasOwnProperty.call(raw, "fileToken") || Object.prototype.hasOwnProperty.call(raw, "FileToken")) {
      this.FileToken = mergeTokenConfigFromRaw(this.FileToken, raw.fileToken ?? raw.FileToken);
    }

    if (
      Object.prototype.hasOwnProperty.call(raw, "verificationTemplate") ||
      Object.prototype.hasOwnProperty.call(raw, "VerificationTemplate")
    ) {
      this.VerificationTemplate = mergeEmailTemplate(
        this.VerificationTemplate,
        raw.verificationTemplate ?? raw.VerificationTemplate,
      );
    }
    if (
      Object.prototype.hasOwnProperty.call(raw, "resetPasswordTemplate") ||
      Object.prototype.hasOwnProperty.call(raw, "ResetPasswordTemplate")
    ) {
      this.ResetPasswordTemplate = mergeEmailTemplate(
        this.ResetPasswordTemplate,
        raw.resetPasswordTemplate ?? raw.ResetPasswordTemplate,
      );
    }
    if (
      Object.prototype.hasOwnProperty.call(raw, "confirmEmailChangeTemplate") ||
      Object.prototype.hasOwnProperty.call(raw, "ConfirmEmailChangeTemplate")
    ) {
      this.ConfirmEmailChangeTemplate = mergeEmailTemplate(
        this.ConfirmEmailChangeTemplate,
        raw.confirmEmailChangeTemplate ?? raw.ConfirmEmailChangeTemplate,
      );
    }
  }

  private applyAuthOptions(options: CollectionAuthOptions): void {
    this.AuthRule = options.AuthRule;
    this.ManageRule = options.ManageRule;
    this.AuthAlert = options.AuthAlert;
    this.OAuth2 = options.OAuth2;
    this.PasswordAuth = options.PasswordAuth;
    this.MFA = options.MFA;
    this.OTP = options.OTP;
    this.AuthToken = options.AuthToken;
    this.PasswordResetToken = options.PasswordResetToken;
    this.EmailChangeToken = options.EmailChangeToken;
    this.VerificationToken = options.VerificationToken;
    this.FileToken = options.FileToken;
    this.VerificationTemplate = options.VerificationTemplate;
    this.ResetPasswordTemplate = options.ResetPasswordTemplate;
    this.ConfirmEmailChangeTemplate = options.ConfirmEmailChangeTemplate;
  }

  private rawOptions(): Record<string, unknown> {
    if (this.IsView()) {
      return { viewQuery: this.ViewQuery };
    }

    if (this.IsAuth()) {
      return this.rawAuthOptions();
    }

    return {};
  }

  private rawAuthOptions(): Record<string, unknown> {
    return {
      authRule: this.AuthRule,
      manageRule: this.ManageRule,
      authAlert: serializeAuthAlert(this.AuthAlert),
      oauth2: serializeOAuth2(this.OAuth2, false),
      passwordAuth: serializePasswordAuth(this.PasswordAuth),
      mfa: serializeMFA(this.MFA),
      otp: serializeOTP(this.OTP),
      authToken: serializeToken(this.AuthToken, false),
      passwordResetToken: serializeToken(this.PasswordResetToken, false),
      emailChangeToken: serializeToken(this.EmailChangeToken, false),
      verificationToken: serializeToken(this.VerificationToken, false),
      fileToken: serializeToken(this.FileToken, false),
      verificationTemplate: serializeEmailTemplate(this.VerificationTemplate),
      resetPasswordTemplate: serializeEmailTemplate(this.ResetPasswordTemplate),
      confirmEmailChangeTemplate: serializeEmailTemplate(this.ConfirmEmailChangeTemplate),
    };
  }

  private safeAuthOptions(): Record<string, unknown> {
    return {
      authRule: this.AuthRule,
      manageRule: this.ManageRule,
      authAlert: serializeAuthAlert(this.AuthAlert),
      oauth2: serializeOAuth2(this.OAuth2, true),
      passwordAuth: serializePasswordAuth(this.PasswordAuth),
      mfa: serializeMFA(this.MFA),
      otp: serializeOTP(this.OTP),
      authToken: serializeToken(this.AuthToken, true),
      passwordResetToken: serializeToken(this.PasswordResetToken, true),
      emailChangeToken: serializeToken(this.EmailChangeToken, true),
      verificationToken: serializeToken(this.VerificationToken, true),
      fileToken: serializeToken(this.FileToken, true),
      verificationTemplate: serializeEmailTemplate(this.VerificationTemplate),
      resetPasswordTemplate: serializeEmailTemplate(this.ResetPasswordTemplate),
      confirmEmailChangeTemplate: serializeEmailTemplate(this.ConfirmEmailChangeTemplate),
    };
  }
}

export function NewCollection(type: string, name: string, id = ""): Collection {
  switch (type) {
    case CollectionTypeAuth:
      return NewAuthCollection(name, id);
    case CollectionTypeView:
      return NewViewCollection(name, id);
    default:
      return NewBaseCollection(name, id);
  }
}

export function NewBaseCollection(name: string, id = ""): Collection {
  const collection = new Collection({ id, name, type: CollectionTypeBase });
  collection.markNew(true);
  collection.initDefaultId();
  collection.initDefaultFields();
  return collection;
}

export function NewAuthCollection(name: string, id = ""): Collection {
  const collection = new Collection({ id, name, type: CollectionTypeAuth });
  collection.markNew(true);
  collection.initDefaultId();
  collection.initDefaultFields();
  collection.setDefaultAuthOptions();
  return collection;
}

export function NewViewCollection(name: string, id = ""): Collection {
  const collection = new Collection({ id, name, type: CollectionTypeView });
  collection.markNew(true);
  collection.initDefaultId();
  collection.initDefaultFields();
  return collection;
}

export function parseCollectionFields(raw: unknown): CollectionField[] {
  if (!Array.isArray(raw)) {
    return [];
  }

  const fields: CollectionField[] = [];
  for (const entry of raw) {
    if (!entry || typeof entry !== "object") {
      continue;
    }
    const record = entry as Record<string, unknown>;
    const name = typeof record.name === "string" ? record.name : typeof record.Name === "string" ? record.Name : "";
    if (!name) {
      continue;
    }
    fields.push({
      name,
      type: typeof record.type === "string" ? record.type : typeof record.Type === "string" ? record.Type : "",
      system: Boolean(record.system ?? record.System),
      hidden: Boolean(record.hidden ?? record.Hidden),
      raw: record,
    });
  }

  return fields;
}

export function normalizeCollectionFields(collection: Collection): void {
  if (collection.Fields.length === 0 && collection.fields.length > 0) {
    try {
      collection.Fields = FieldsList.fromJSON(JSON.stringify(collection.fields));
    } catch {
      collection.Fields = new FieldsList();
    }
  }

  if (collection.Fields.length > 0) {
    collection.fields = parseCollectionFields(collection.Fields.toJSON());
  }
}

export function collectionFromRow(row: CollectionRow): Collection {
  let fieldsRaw: unknown = [];
  let fieldsList = new FieldsList();
  if (typeof row.fields === "string") {
    try {
      fieldsRaw = JSON.parse(row.fields);
    } catch {
      fieldsRaw = [];
    }
    try {
      fieldsList = FieldsList.fromJSON(row.fields);
    } catch {
      fieldsList = new FieldsList();
    }
  }

  let indexes: unknown = [];
  if (typeof row.indexes === "string") {
    try {
      indexes = JSON.parse(row.indexes);
    } catch {
      indexes = [];
    }
  }

  const collection = new Collection({
    id: row.id,
    name: row.name,
    type: row.type,
    system: toBoolValue(row.system),
    fields: parseCollectionFields(fieldsRaw),
    Fields: fieldsList,
    indexes: Array.isArray(indexes) ? (indexes.filter((value) => typeof value === "string") as string[]) : [],
    listRule: row.listRule ?? null,
    viewRule: row.viewRule ?? null,
    createRule: row.createRule ?? null,
    updateRule: row.updateRule ?? null,
    deleteRule: row.deleteRule ?? null,
    created: row.created ? ParseDateTime(row.created) : undefined,
    updated: row.updated ? ParseDateTime(row.updated) : undefined,
  });

  if (typeof row.options === "string") {
    collection.RawOptions = JSONRaw.parse(row.options);
    collection.unmarshalRawOptions();
  }

  collection.markNew(false);
  return collection;
}

export function applyCollectionData(collection: Collection, data: Record<string, unknown>): void {
  if (typeof data.name === "string") {
    collection.name = data.name;
  }
  if (typeof data.type === "string") {
    collection.type = data.type;
  }
  if (typeof data.system === "boolean") {
    collection.system = data.system;
  } else if (typeof data.system === "number") {
    collection.system = Boolean(data.system);
  }
  if (Array.isArray(data.fields)) {
    try {
      collection.Fields = FieldsList.fromJSON(JSON.stringify(data.fields));
    } catch {
      collection.Fields = new FieldsList();
    }
  }
  if (Array.isArray(data.indexes)) {
    collection.indexes = data.indexes.filter((value) => typeof value === "string") as string[];
  }
  if (data.listRule === null || typeof data.listRule === "string") {
    collection.listRule = data.listRule as string | null;
  }
  if (data.viewRule === null || typeof data.viewRule === "string") {
    collection.viewRule = data.viewRule as string | null;
  }
  if (data.createRule === null || typeof data.createRule === "string") {
    collection.createRule = data.createRule as string | null;
  }
  if (data.updateRule === null || typeof data.updateRule === "string") {
    collection.updateRule = data.updateRule as string | null;
  }
  if (data.deleteRule === null || typeof data.deleteRule === "string") {
    collection.deleteRule = data.deleteRule as string | null;
  }
  if (typeof data.options === "object" && data.options) {
    collection.options = data.options as Record<string, unknown>;
  }
  collection.options = data;
}

function mergeTokenConfig(current: TokenConfigValue, raw: unknown): TokenConfigValue {
  const merged = new TokenConfigValue(current.Secret, current.Duration);
  if (!raw || typeof raw !== "object") {
    return merged;
  }
  const record = raw as Record<string, unknown>;
  if (Object.prototype.hasOwnProperty.call(record, "secret") || Object.prototype.hasOwnProperty.call(record, "Secret")) {
    merged.Secret = toStringValue(record.secret ?? record.Secret);
  }
  if (Object.prototype.hasOwnProperty.call(record, "duration") || Object.prototype.hasOwnProperty.call(record, "Duration")) {
    merged.Duration = toNumberValue(record.duration ?? record.Duration);
  }
  return merged;
}

function mergeTokenConfigFromRaw(current: TokenConfigValue, raw: unknown): TokenConfigValue {
  if (!raw || typeof raw !== "object") {
    return new TokenConfigValue(current.Secret, current.Duration);
  }
  return mergeTokenConfig(current, raw);
}

function mergeEmailTemplate(current: EmailTemplate, raw: unknown): EmailTemplate {
  const merged = new EmailTemplate();
  merged.Subject = current.Subject;
  merged.Body = current.Body;
  if (!raw || typeof raw !== "object") {
    return merged;
  }
  const record = raw as Record<string, unknown>;
  if (Object.prototype.hasOwnProperty.call(record, "subject") || Object.prototype.hasOwnProperty.call(record, "Subject")) {
    merged.Subject = toStringValue(record.subject ?? record.Subject);
  }
  if (Object.prototype.hasOwnProperty.call(record, "body") || Object.prototype.hasOwnProperty.call(record, "Body")) {
    merged.Body = toStringValue(record.body ?? record.Body);
  }
  return merged;
}

function mergeAuthAlertConfig(current: AuthAlertConfig, raw: unknown): AuthAlertConfig {
  const merged = new AuthAlertConfig();
  merged.Enabled = current.Enabled;
  merged.EmailTemplate = current.EmailTemplate;
  if (!raw || typeof raw !== "object") {
    return merged;
  }
  const record = raw as Record<string, unknown>;
  if (Object.prototype.hasOwnProperty.call(record, "enabled") || Object.prototype.hasOwnProperty.call(record, "Enabled")) {
    merged.Enabled = Boolean(record.enabled ?? record.Enabled);
  }
  if (
    Object.prototype.hasOwnProperty.call(record, "emailTemplate") ||
    Object.prototype.hasOwnProperty.call(record, "EmailTemplate")
  ) {
    merged.EmailTemplate = mergeEmailTemplate(merged.EmailTemplate, record.emailTemplate ?? record.EmailTemplate);
  }
  return merged;
}

function mergePasswordAuthConfig(current: PasswordAuthConfig, raw: unknown): PasswordAuthConfig {
  const merged = new PasswordAuthConfig();
  merged.Enabled = current.Enabled;
  merged.IdentityFields = current.IdentityFields ? [...current.IdentityFields] : current.IdentityFields;
  if (!raw || typeof raw !== "object") {
    return merged;
  }
  const record = raw as Record<string, unknown>;
  if (Object.prototype.hasOwnProperty.call(record, "enabled") || Object.prototype.hasOwnProperty.call(record, "Enabled")) {
    merged.Enabled = Boolean(record.enabled ?? record.Enabled);
  }
  if (
    Object.prototype.hasOwnProperty.call(record, "identityFields") ||
    Object.prototype.hasOwnProperty.call(record, "IdentityFields")
  ) {
    const fields = record.identityFields ?? record.IdentityFields;
    merged.IdentityFields = fields == null ? null : toUniqueStringSlice(fields);
  }
  return merged;
}

function mergeMFAConfig(current: MFAConfig, raw: unknown): MFAConfig {
  const merged = new MFAConfig();
  merged.Enabled = current.Enabled;
  merged.Duration = current.Duration;
  merged.Rule = current.Rule;
  if (!raw || typeof raw !== "object") {
    return merged;
  }
  const record = raw as Record<string, unknown>;
  if (Object.prototype.hasOwnProperty.call(record, "enabled") || Object.prototype.hasOwnProperty.call(record, "Enabled")) {
    merged.Enabled = Boolean(record.enabled ?? record.Enabled);
  }
  if (Object.prototype.hasOwnProperty.call(record, "duration") || Object.prototype.hasOwnProperty.call(record, "Duration")) {
    merged.Duration = toNumberValue(record.duration ?? record.Duration);
  }
  if (Object.prototype.hasOwnProperty.call(record, "rule") || Object.prototype.hasOwnProperty.call(record, "Rule")) {
    merged.Rule = toStringValue(record.rule ?? record.Rule);
  }
  return merged;
}

function mergeOTPConfig(current: OTPConfig, raw: unknown): OTPConfig {
  const merged = new OTPConfig();
  merged.Enabled = current.Enabled;
  merged.Duration = current.Duration;
  merged.Length = current.Length;
  merged.EmailTemplate = current.EmailTemplate;
  if (!raw || typeof raw !== "object") {
    return merged;
  }
  const record = raw as Record<string, unknown>;
  if (Object.prototype.hasOwnProperty.call(record, "enabled") || Object.prototype.hasOwnProperty.call(record, "Enabled")) {
    merged.Enabled = Boolean(record.enabled ?? record.Enabled);
  }
  if (Object.prototype.hasOwnProperty.call(record, "duration") || Object.prototype.hasOwnProperty.call(record, "Duration")) {
    merged.Duration = toNumberValue(record.duration ?? record.Duration);
  }
  if (Object.prototype.hasOwnProperty.call(record, "length") || Object.prototype.hasOwnProperty.call(record, "Length")) {
    merged.Length = toNumberValue(record.length ?? record.Length);
  }
  if (
    Object.prototype.hasOwnProperty.call(record, "emailTemplate") ||
    Object.prototype.hasOwnProperty.call(record, "EmailTemplate")
  ) {
    merged.EmailTemplate = mergeEmailTemplate(merged.EmailTemplate, record.emailTemplate ?? record.EmailTemplate);
  }
  return merged;
}

function mergeOAuth2Config(current: OAuth2Config, raw: unknown): OAuth2Config {
  const merged = new OAuth2Config();
  merged.Enabled = current.Enabled;
  merged.Providers = current.Providers;
  merged.MappedFields = { ...current.MappedFields };

  if (!raw || typeof raw !== "object") {
    return merged;
  }
  const record = raw as Record<string, unknown>;

  if (Object.prototype.hasOwnProperty.call(record, "enabled") || Object.prototype.hasOwnProperty.call(record, "Enabled")) {
    merged.Enabled = Boolean(record.enabled ?? record.Enabled);
  }

  if (Object.prototype.hasOwnProperty.call(record, "providers") || Object.prototype.hasOwnProperty.call(record, "Providers")) {
    const providers = record.providers ?? record.Providers;
    if (Array.isArray(providers)) {
      merged.Providers = providers.map((item) => normalizeOAuth2ProviderConfig(item));
    } else {
      merged.Providers = null;
    }
  }

  if (
    Object.prototype.hasOwnProperty.call(record, "mappedFields") ||
    Object.prototype.hasOwnProperty.call(record, "MappedFields")
  ) {
    const fields = record.mappedFields ?? record.MappedFields;
    if (fields && typeof fields === "object") {
      const mapped = fields as Record<string, unknown>;
      merged.MappedFields = {
        Id: Object.prototype.hasOwnProperty.call(mapped, "id")
          ? toStringValue(mapped.id)
          : Object.prototype.hasOwnProperty.call(mapped, "Id")
            ? toStringValue(mapped.Id)
            : merged.MappedFields.Id,
        Name: Object.prototype.hasOwnProperty.call(mapped, "name")
          ? toStringValue(mapped.name)
          : Object.prototype.hasOwnProperty.call(mapped, "Name")
            ? toStringValue(mapped.Name)
            : merged.MappedFields.Name,
        Username: Object.prototype.hasOwnProperty.call(mapped, "username")
          ? toStringValue(mapped.username)
          : Object.prototype.hasOwnProperty.call(mapped, "Username")
            ? toStringValue(mapped.Username)
            : merged.MappedFields.Username,
        AvatarURL: Object.prototype.hasOwnProperty.call(mapped, "avatarURL")
          ? toStringValue(mapped.avatarURL)
          : Object.prototype.hasOwnProperty.call(mapped, "AvatarURL")
            ? toStringValue(mapped.AvatarURL)
            : merged.MappedFields.AvatarURL,
      };
    }
  }

  return merged;
}

function serializeEmailTemplate(template: EmailTemplate): Record<string, unknown> {
  return {
    subject: template.Subject,
    body: template.Body,
  };
}

function serializeAuthAlert(alert: AuthAlertConfig): Record<string, unknown> {
  return {
    enabled: alert.Enabled,
    emailTemplate: serializeEmailTemplate(alert.EmailTemplate),
  };
}

function serializePasswordAuth(config: PasswordAuthConfig): Record<string, unknown> {
  return {
    enabled: config.Enabled,
    identityFields: config.IdentityFields,
  };
}

function serializeMFA(config: MFAConfig): Record<string, unknown> {
  return {
    enabled: config.Enabled,
    duration: config.Duration,
    rule: config.Rule,
  };
}

function serializeOTP(config: OTPConfig): Record<string, unknown> {
  return {
    enabled: config.Enabled,
    duration: config.Duration,
    length: config.Length,
    emailTemplate: serializeEmailTemplate(config.EmailTemplate),
  };
}

function serializeOAuth2(config: OAuth2Config, safe: boolean): Record<string, unknown> {
  const providers = config.Providers ?? (safe ? [] : null);
  const mappedProviders = providers
    ? providers.map((provider) => {
        const record: Record<string, unknown> = {
          pkce: provider.PKCE,
          name: provider.Name,
          clientId: provider.ClientId,
          authURL: provider.AuthURL,
          tokenURL: provider.TokenURL,
          userInfoURL: provider.UserInfoURL,
          displayName: provider.DisplayName,
          extra: provider.Extra,
        };
        if (!safe && provider.ClientSecret) {
          record.clientSecret = provider.ClientSecret;
        }
        return record;
      })
    : null;

  return {
    providers: mappedProviders,
    mappedFields: {
      id: config.MappedFields.Id,
      name: config.MappedFields.Name,
      username: config.MappedFields.Username,
      avatarURL: config.MappedFields.AvatarURL,
    },
    enabled: config.Enabled,
  };
}

function serializeToken(config: TokenConfigValue, safe: boolean): Record<string, unknown> {
  const record: Record<string, unknown> = {
    duration: config.Duration,
  };
  if (!safe && config.Secret) {
    record.secret = config.Secret;
  }
  return record;
}

function crc32Checksum(value: string): string {
  return String(Bun.hash.crc32(value));
}
