// Ported from pocketbase/core/collection_import.go

import type { App } from "./app.ts";
import { ValidationErrors, newError } from "../internal/compat/validation.ts";
import { ParseDateTime } from "../tools/types/index.ts";
import { Collection, collectionFromRow, normalizeCollectionFields, type CollectionRow } from "./collection_model.ts";
import { validateCollection, validateCollectionSync } from "./collection_validate.ts";

// ImportCollectionsByMarshaledJSON is the same as importCollections
// but accept marshaled json array as import data (usually used for the autogenerated snapshots).
export async function importCollectionsByMarshaledJSON(
  app: App,
  rawSliceOfMaps: string | Uint8Array,
  deleteMissing: boolean,
): Promise<Error | null> {
  try {
    const decoded = typeof rawSliceOfMaps === "string" ? rawSliceOfMaps : new TextDecoder().decode(rawSliceOfMaps);
    const data = JSON.parse(decoded) as Array<Record<string, unknown>>;
    if (!Array.isArray(data)) {
      return new Error("invalid collections data");
    }
    return await importCollections(app, data, deleteMissing);
  } catch (error) {
    return error as Error;
  }
}

// ImportCollectionsByMarshaledJSONSync is the synchronous equivalent of
// ImportCollectionsByMarshaledJSON, used by JSVM migrations.
export function importCollectionsByMarshaledJSONSync(
  app: App,
  rawSliceOfMaps: string | Uint8Array,
  deleteMissing: boolean,
): Error | null {
  try {
    const decoded = typeof rawSliceOfMaps === "string" ? rawSliceOfMaps : new TextDecoder().decode(rawSliceOfMaps);
    const data = JSON.parse(decoded) as Array<Record<string, unknown>>;
    if (!Array.isArray(data)) {
      return new Error("invalid collections data");
    }
    return importCollectionsSync(app, data, deleteMissing);
  } catch (error) {
    return error as Error;
  }
}

// ImportCollections imports the provided collections data in a single transaction.
//
// For existing matching collections, the imported data is unmarshaled on top of the existing model.
//
// NB! If deleteMissing is true, ALL NON-SYSTEM COLLECTIONS AND SCHEMA FIELDS,
// that are not present in the imported configuration, WILL BE DELETED
// (this includes their related records data).
export async function importCollections(
  app: App,
  toImport: Array<Record<string, unknown>>,
  deleteMissing: boolean,
): Promise<Error | null> {
  if (toImport.length === 0) {
    return new Error("no collections to import");
  }

  const importedCollections: Collection[] = Array.from({ length: toImport.length });
  const mappedImported = new Map<string, Collection>();

  for (let i = 0; i < toImport.length; i += 1) {
    const data = (toImport[i] ?? {}) as Record<string, unknown>;
    let identifier = typeof data.id === "string" ? data.id : "";
    if (!identifier) {
      identifier = typeof data.name === "string" ? data.name : "";
    }

    const existing = identifier ? app.findCollectionByNameOrIdOrNull(identifier) : null;
    const imported = existing ? (app.findCollectionById(existing.id) ?? existing) : new Collection();
    const normalizedData = normalizeImportedCollectionData(data, deleteMissing);

    applyImportData(imported, normalizedData);

    if (existing) {
      for (const field of existing.Fields) {
        if (!field.GetSystem() && deleteMissing) {
          continue;
        }
        if (!imported.Fields.GetById(field.GetId())) {
          const found = imported.Fields.GetByName(field.GetName());
          if (found && found.Type() === field.Type()) {
            found.SetId(field.GetId());
          }
          imported.Fields.Add(field);
        }
      }
    }

    imported.IntegrityChecks(false);
    importedCollections[i] = imported;
    mappedImported.set(imported.id, imported);
  }

  importedCollections.sort((left, right) => {
    const leftView = left.IsView();
    const rightView = right.IsView();
    if (leftView !== rightView) {
      return leftView ? 1 : -1;
    }

    const created = left.created.compare(right.created);
    if (created !== 0) {
      return created;
    }

    return left.updated.compare(right.updated);
  });

  return app.RunInTransaction(async (txApp) => {
    const rows = txApp
      .db()
      .query(
        "select id, name, system, type, fields, indexes, listRule, viewRule, createRule, updateRule, deleteRule, options, created, updated from _collections order by updated asc",
      )
      .all() as CollectionRow[];
    const existingCollections = rows.map((row) => collectionFromRow(row));
    const mappedExisting = new Map<string, Collection>();

    for (const existing of existingCollections) {
      existing.IntegrityChecks(false);
      mappedExisting.set(existing.id, existing);
    }

    if (deleteMissing) {
      for (const existing of existingCollections) {
        if (mappedImported.get(existing.id) || existing.system) {
          continue;
        }
        const err = await txApp.Delete(existing);
        if (err) {
          return err;
        }
      }
    }

    for (const imported of importedCollections) {
      const err = await txApp.SaveNoValidate(imported);
      if (err) {
        return new Error(`failed to save collection "${imported.name}": ${err.message}`);
      }
    }

    for (const imported of importedCollections) {
      const original = mappedExisting.get(imported.id) ?? imported;
      const validationErr = await validateCollection(txApp, imported, original);
      if (validationErr) {
        const serialized = JSON.stringify(validationErr, null, 2);
        return new ValidationErrors({
          collections: newError(
            "validation_collections_import_failure",
            `Data validations failed for collection "${imported.name}" (${imported.id}):\n${serialized}`,
          ),
        });
      }
    }

    return null;
  });
}

// ImportCollectionsSync imports the provided collections data synchronously.
//
// It mirrors ImportCollections for JSVM migrations where the migration runner
// expects migration callbacks to finish before marking them applied.
export function importCollectionsSync(
  app: App,
  toImport: Array<Record<string, unknown>>,
  deleteMissing: boolean,
): Error | null {
  if (toImport.length === 0) {
    return new Error("no collections to import");
  }

  const importedCollections: Collection[] = Array.from({ length: toImport.length });
  const mappedImported = new Map<string, Collection>();

  for (let i = 0; i < toImport.length; i += 1) {
    const data = (toImport[i] ?? {}) as Record<string, unknown>;
    let identifier = typeof data.id === "string" ? data.id : "";
    if (!identifier) {
      identifier = typeof data.name === "string" ? data.name : "";
    }

    const existing = identifier ? app.findCollectionByNameOrIdOrNull(identifier) : null;
    const imported = existing ? (app.findCollectionById(existing.id) ?? existing) : new Collection();
    const normalizedData = normalizeImportedCollectionData(data, deleteMissing);

    applyImportData(imported, normalizedData);

    if (existing) {
      for (const field of existing.Fields) {
        if (!field.GetSystem() && deleteMissing) {
          continue;
        }
        if (!imported.Fields.GetById(field.GetId())) {
          const found = imported.Fields.GetByName(field.GetName());
          if (found && found.Type() === field.Type()) {
            found.SetId(field.GetId());
          }
          imported.Fields.Add(field);
        }
      }
    }

    imported.IntegrityChecks(false);
    importedCollections[i] = imported;
    mappedImported.set(imported.id, imported);
  }

  importedCollections.sort((left, right) => {
    const leftView = left.IsView();
    const rightView = right.IsView();
    if (leftView !== rightView) {
      return leftView ? 1 : -1;
    }

    const created = left.created.compare(right.created);
    if (created !== 0) {
      return created;
    }

    return left.updated.compare(right.updated);
  });

  return app.RunInTransactionSync((txApp) => {
    const rows = txApp
      .db()
      .query(
        "select id, name, system, type, fields, indexes, listRule, viewRule, createRule, updateRule, deleteRule, options, created, updated from _collections order by updated asc",
      )
      .all() as CollectionRow[];
    const existingCollections = rows.map((row) => collectionFromRow(row));
    const mappedExisting = new Map<string, Collection>();

    for (const existing of existingCollections) {
      existing.IntegrityChecks(false);
      mappedExisting.set(existing.id, existing);
    }

    if (deleteMissing) {
      for (const existing of existingCollections) {
        if (mappedImported.get(existing.id) || existing.system) {
          continue;
        }
        const err = txApp.DeleteSync(existing);
        if (err) {
          return err;
        }
      }
    }

    for (const imported of importedCollections) {
      const err = txApp.SaveNoValidateSync(imported);
      if (err) {
        return new Error(`failed to save collection "${imported.name}": ${err.message}`);
      }
    }

    for (const imported of importedCollections) {
      const original = mappedExisting.get(imported.id) ?? imported;
      const validationErr = validateCollectionSync(txApp, imported, original);
      if (validationErr) {
        const serialized = JSON.stringify(validationErr, null, 2);
        return new ValidationErrors({
          collections: newError(
            "validation_collections_import_failure",
            `Data validations failed for collection "${imported.name}" (${imported.id}):\n${serialized}`,
          ),
        });
      }
    }

    return null;
  });
}

function normalizeImportedCollectionData(data: Record<string, unknown>, deleteMissing: boolean): Record<string, unknown> {
  if (!deleteMissing) {
    return data;
  }

  const hasFields = Object.prototype.hasOwnProperty.call(data, "fields");
  if (hasFields && data.fields != null) {
    return data;
  }

  return { ...data, fields: [] };
}

function applyImportData(collection: Collection, data: Record<string, unknown>): void {
  collection.UnmarshalJSON(data);
  if (typeof data.id === "string") {
    collection.id = data.id;
  }
  if (data.created != null) {
    collection.created = ParseDateTime(data.created);
  }
  if (data.updated != null) {
    collection.updated = ParseDateTime(data.updated);
  }

  normalizeCollectionFields(collection);
}
