// Ported from pocketbase/core/db_model.go

// Model defines an interface with common methods that all db models should have.
//
// Note: for simplicity composite pk are not supported.
export type Model = {
  TableName: () => string;
  PK: () => unknown;
  LastSavedPK: () => unknown;
  IsNew: () => boolean;
  MarkAsNew: () => void;
  MarkAsNotNew: () => void;
};

// BaseModel defines a base struct that is intended to be embedded into other custom models.
export class BaseModel {
  // Id is the primary key of the model.
  // It is usually autogenerated by the parent model implementation.
  Id = "";

  #lastSavedPK = "";

  // LastSavedPK returns the last saved primary key of the model.
  //
  // Its value is updated to the latest PK value after MarkAsNotNew() or PostScan() calls.
  LastSavedPK(): string {
    return this.#lastSavedPK;
  }

  PK(): string {
    return this.Id;
  }

  // IsNew indicates what type of db query (insert or update)
  // should be used with the model instance.
  IsNew(): boolean {
    return this.#lastSavedPK === "";
  }

  // MarkAsNew clears the pk field and marks the current model as "new"
  // (aka. forces m.IsNew() to be true).
  MarkAsNew(): void {
    this.#lastSavedPK = "";
  }

  // MarkAsNotNew set the pk field to the Id value and marks the current model
  // as NOT "new" (aka. forces m.IsNew() to be false).
  MarkAsNotNew(): void {
    this.#lastSavedPK = this.Id;
  }

  // PostScan implements the [dbx.PostScanner] interface.
  //
  // It is usually executed right after the model is populated with the db row values.
  PostScan(): Error | null {
    this.MarkAsNotNew();
    return null;
  }
}
