// Ported from pocketbase/core/record_model_superusers.go (adapted as a helper for BaseApp).

import type { App } from "./app.ts";
import type { CollectionEvent, MailerRecordEvent, RecordEvent } from "./events.ts";
import { NewBadRequestError } from "../tools/router/api_error.ts";
import { CollectionNameSuperusers } from "./collection.ts";
import { ModelEventTypeCreate } from "./events.ts";

// DefaultInstallerEmail is the default superuser email address
// for the initial autogenerated superuser account.
export const DefaultInstallerEmail = "__pbinstaller@example.com";

export function registerSuperuserHooks(app: App): void {
  app.OnRecordDelete([CollectionNameSuperusers]).Bind({
    Id: "pbSuperusersRecordDelete",
    Priority: -99,
    Func: async (e: RecordEvent) => {
      const originalApp = e.App;
      const txErr = await e.App.RunInTransaction(async (txApp) => {
        e.App = txApp;

        let total = 0;
        try {
          total = e.App.CountRecords(CollectionNameSuperusers);
        } catch (error) {
          const message = error instanceof Error ? error.message : String(error);
          return new Error(`failed to fetch total superusers count: ${message}`);
        }

        if (total === 1) {
          return NewBadRequestError("You can't delete the only existing superuser", null);
        }

        return (await e.Next()) as Error | null;
      });
      e.App = originalApp;
      return txErr;
    },
  });

  const recordSaveHandler = {
    Id: "pbSuperusersRecordSaveExec",
    Priority: -99,
    Func: async (e: RecordEvent) => {
      if (e.Record) {
        e.Record.SetVerified(true);
      }

      const err = (await e.Next()) as Error | null;
      if (err) {
        return err;
      }

      if (e.Type === ModelEventTypeCreate && e.Record && e.Record.Email() !== DefaultInstallerEmail) {
        let installer = null;
        try {
          installer = app.FindAuthRecordByEmail(CollectionNameSuperusers, DefaultInstallerEmail);
        } catch (error) {
          if (error instanceof Error && error.message === "record not found") {
            return null;
          }
          e.App.Logger().Warn("Failed to fetch installer superuser", "error", error);
          return null;
        }

        const deleteErr = await e.App.Delete(installer);
        if (deleteErr) {
          e.App.Logger().Warn("Failed to delete installer superuser", "error", deleteErr);
        }
      }

      return null;
    },
  };
  app.OnRecordCreateExecute([CollectionNameSuperusers]).Bind(recordSaveHandler);
  app.OnRecordUpdateExecute([CollectionNameSuperusers]).Bind(recordSaveHandler);

  app.OnMailerRecordPasswordResetSend([CollectionNameSuperusers]).Bind({
    Id: "pbSuperusersInstallerPasswordReset",
    Func: (e: MailerRecordEvent) => {
      if (e.Record?.Email() === DefaultInstallerEmail) {
        return new Error("cannot reset the password for the installer superuser");
      }

      return e.Next();
    },
  });

  const collectionSaveHandler = {
    Id: "pbSuperusersCollectionSaveExec",
    Priority: 99,
    Func: (e: CollectionEvent) => {
      if (!e.Collection) {
        return e.Next();
      }

      e.Collection.name = CollectionNameSuperusers;
      e.Collection.OAuth2.Enabled = false;
      e.Collection.OAuth2.Providers = null;
      e.Collection.PasswordAuth.Enabled = true;

      if (e.Collection.OTP.Enabled) {
        e.Collection.MFA.Enabled = true;
      }

      return e.Next();
    },
  };
  app.OnCollectionCreateExecute([CollectionNameSuperusers]).Bind(collectionSaveHandler);
  app.OnCollectionUpdateExecute([CollectionNameSuperusers]).Bind(collectionSaveHandler);
}
