// Ported from pocketbase/tools/hook/hook.go

import type { Resolver } from "./event.ts";
import { profileEnabled, recordProfile, recordProfileSelf } from "../perf/profile.ts";
import { randomString } from "../security/random.ts";
import { Event } from "./event.ts";

export type HandlerFunc<T extends Resolver> = (event: T) => unknown;

// Handler defines a single Hook handler.
// Multiple handlers can share the same id.
// If Id is not explicitly set it will be autogenerated by Hook.Add and Hook.AddHandler.
export type Handler<T extends Resolver> = {
  Func: HandlerFunc<T>;
  Id?: string;
  Priority?: number;
};

// Hook defines a generic concurrent safe structure for managing event hooks.
//
// When using custom event it must embed the base [hook.Event].
//
// Example:
//
//	type CustomEvent struct {
//		hook.Event
//		SomeField int
//	}
//
//	h := Hook[*CustomEvent]{}
//
//	h.BindFunc(func(e *CustomEvent) error {
//		println(e.SomeField)
//
//		return e.Next()
//	})
//
//	h.Trigger(&CustomEvent{ SomeField: 123 })
export class Hook<T extends Resolver> {
  #handlers: Handler<T>[] = [];

  Bind(handler: Handler<T>): string {
    let exists = false;
    if (!handler.Id) {
      handler.Id = generateHookId();
      while (this.#handlers.some((existing) => existing.Id === handler.Id)) {
        handler.Id = generateHookId();
      }
    } else {
      const index = this.#handlers.findIndex((existing) => existing.Id === handler.Id);
      if (index >= 0) {
        this.#handlers[index] = handler;
        exists = true;
      }
    }

    if (!exists) {
      this.#handlers.push(handler);
    }

    this.#handlers.sort((a, b) => (a.Priority ?? 0) - (b.Priority ?? 0));
    return handler.Id ?? "";
  }

  BindFunc(fn: HandlerFunc<T>): string {
    return this.Bind({ Func: fn });
  }

  Unbind(...idsToRemove: string[]): void {
    if (idsToRemove.length === 0) {
      return;
    }
    const idsToRemoveSet = new Set(idsToRemove);
    this.#handlers = this.#handlers.filter((handler) => !idsToRemoveSet.has(handler.Id ?? ""));
  }

  UnbindAll(): void {
    this.#handlers = [];
  }

  Length(): number {
    return this.#handlers.length;
  }

  Trigger(event: T, ...oneOffHandlerFuncs: HandlerFunc<T>[]): unknown {
    const handlers: Array<{ func: HandlerFunc<T>; id?: string }> = [];
    for (const handler of this.#handlers) {
      handlers.push({ func: handler.Func, id: handler.Id });
    }
    for (const handler of oneOffHandlerFuncs) {
      handlers.push({ func: handler });
    }

    event.setNextFunc(null);
    const doProfile = profileEnabled();

    for (let i = handlers.length - 1; i >= 0; i -= 1) {
      const handler = handlers[i];
      if (!handler) {
        continue;
      }
      const old = event.nextFunc();
      event.setNextFunc(() => {
        event.setNextFunc(old);
        if (!doProfile) {
          return handler.func(event);
        }
        const label = resolveHandlerLabel(handler);
        const started = performance.now();
        let downstreamMs = 0;
        const nextFunc = event.nextFunc();
        if (nextFunc) {
          event.setNextFunc(() => {
            event.setNextFunc(nextFunc);
            const downstreamStart = performance.now();
            try {
              const result = nextFunc();
              if (result && typeof (result as Promise<unknown>).then === "function") {
                return (result as Promise<unknown>).finally(() => {
                  downstreamMs += performance.now() - downstreamStart;
                });
              }
              downstreamMs += performance.now() - downstreamStart;
              return result;
            } catch (error) {
              downstreamMs += performance.now() - downstreamStart;
              throw error;
            }
          });
        }
        const recordTiming = () => {
          const total = performance.now() - started;
          recordProfile(label, total);
          recordProfileSelf(label, Math.max(0, total - downstreamMs));
        };
        try {
          const result = handler.func(event);
          if (result && typeof (result as Promise<unknown>).then === "function") {
            return (result as Promise<unknown>).finally(recordTiming);
          }
          recordTiming();
          return result;
        } catch (error) {
          recordTiming();
          throw error;
        }
      });
    }

    return event.Next();
  }
}

function generateHookId(): string {
  return randomString(20);
}

function resolveHandlerLabel<T extends Resolver>(handler: { func: HandlerFunc<T>; id?: string }): string {
  if (handler.id) {
    return handler.id;
  }
  const labeled = handler.func as { __hookLabel?: string; name?: string };
  if (typeof labeled.__hookLabel === "string" && labeled.__hookLabel) {
    return labeled.__hookLabel;
  }
  if (labeled.name) {
    return labeled.name;
  }
  return "anonymous";
}

export { Event };
