// Ported from pocketbase/tools/hook/hook.go

import type { Resolver } from "./event.ts";
import { randomString } from "../security/random.ts";
import { Event } from "./event.ts";

export type HandlerFunc<T extends Resolver> = (event: T) => unknown;

// Handler defines a single Hook handler.
// Multiple handlers can share the same id.
// If id is not explicitly set it will be autogenerated by Hook.Add and Hook.AddHandler.
type LowercaseHandler<T extends Resolver> = {
  func: HandlerFunc<T>;
  id?: string;
  priority?: number;
  Func?: HandlerFunc<T>;
  Id?: string;
  Priority?: number;
};

type UppercaseHandler<T extends Resolver> = {
  Func: HandlerFunc<T>;
  Id?: string;
  Priority?: number;
  func?: HandlerFunc<T>;
  id?: string;
  priority?: number;
};

export type Handler<T extends Resolver> = LowercaseHandler<T> | UppercaseHandler<T>;

export type BoundHandler<T extends Resolver> = {
  Func: HandlerFunc<T>;
  Id?: string;
  Priority?: number;
};

type InternalHandler<T extends Resolver> = BoundHandler<T> & {
  // PocketBun perf deviation (behavior-compatible): optional matcher metadata
  // attached by TaggedHook so Hook.Trigger can skip non-matching handlers.
  __pbTagSet?: Set<string> | null;
};

export function normalizeHandler<T extends Resolver>(
  handler: Handler<T> & { __pbTagSet?: Set<string> | null },
): InternalHandler<T> {
  const source = handler as {
    func?: HandlerFunc<T>;
    id?: string;
    priority?: number;
    Func?: HandlerFunc<T>;
    Id?: string;
    Priority?: number;
    __pbTagSet?: Set<string> | null;
  };
  const fn = source.func ?? source.Func;
  if (typeof fn !== "function") {
    throw new TypeError("hook handler func must be a function");
  }

  return {
    Func: fn,
    Id: source.id ?? source.Id,
    Priority: source.priority ?? source.Priority,
    __pbTagSet: source.__pbTagSet,
  };
}

// Hook defines a generic concurrent safe structure for managing event hooks.
//
// When using custom event it must embed the base [hook.Event].
//
// Example:
//
//	type CustomEvent struct {
//		hook.Event
//		SomeField int
//	}
//
//	h := Hook[*CustomEvent]{}
//
//	h.BindFunc(func(e *CustomEvent) error {
//		println(e.SomeField)
//
//		return e.Next()
//	})
//
//	h.Trigger(&CustomEvent{ SomeField: 123 })
export class Hook<T extends Resolver> {
  #handlers: InternalHandler<T>[] = [];

  Bind(handler: Handler<T>): string {
    const internalHandler = normalizeHandler(handler);
    let exists = false;
    if (!internalHandler.Id) {
      internalHandler.Id = generateHookId();
      while (this.#handlers.some((existing) => existing.Id === internalHandler.Id)) {
        internalHandler.Id = generateHookId();
      }
      assignHandlerId(handler, internalHandler.Id);
    } else {
      const index = this.#handlers.findIndex((existing) => existing.Id === internalHandler.Id);
      if (index >= 0) {
        this.#handlers[index] = internalHandler;
        exists = true;
      }
    }

    if (!exists) {
      this.#handlers.push(internalHandler);
    }

    this.#handlers.sort((a, b) => (a.Priority ?? 0) - (b.Priority ?? 0));
    return internalHandler.Id ?? "";
  }

  BindFunc(fn: HandlerFunc<T>): string {
    return this.Bind({ func: fn });
  }

  Unbind(...idsToRemove: string[]): void {
    if (idsToRemove.length === 0) {
      return;
    }
    const idsToRemoveSet = new Set(idsToRemove);
    this.#handlers = this.#handlers.filter((handler) => !idsToRemoveSet.has(handler.Id ?? ""));
  }

  UnbindAll(): void {
    this.#handlers = [];
  }

  Length(): number {
    return this.#handlers.length;
  }

  HasOnlyHandlerId(id: string): boolean {
    return this.#handlers.length === 1 && this.#handlers[0]?.Id === id;
  }

  CanTriggerOn(tagsToCheck: string[]): boolean {
    if (this.#handlers.length === 0) {
      return false;
    }

    for (const handler of this.#handlers) {
      const tagSet = handler.__pbTagSet;
      if (!tagSet || tagSet.size === 0) {
        return true;
      }

      for (const tag of tagsToCheck) {
        if (tagSet.has(tag)) {
          return true;
        }
      }
    }

    return false;
  }

  Trigger(event: T, ...oneOffHandlerFuncs: HandlerFunc<T>[]): unknown {
    event.setNextFunc(null);
    const handlersLen = this.#handlers.length;
    const oneOffLen = oneOffHandlerFuncs.length;
    const tagCache: { tags?: string[] } = {};

    // PocketBun perf deviation (behavior-compatible): avoid temporary handler array/object
    // allocation on the hot path and keep direct next-chain wiring.
    if (handlersLen === 0 && oneOffLen === 1) {
      const single = oneOffHandlerFuncs[0];
      if (!single) {
        return event.Next();
      }
      return single(event);
    }

    // PocketBun perf deviation (behavior-compatible): execute the chain with a
    // single cursor-driven next func to avoid per-handler closure allocations.
    const totalLen = handlersLen + oneOffLen;
    let index = 0;
    const next = (): unknown => {
      while (index < totalLen) {
        const current = index;
        index += 1;
        if (current < handlersLen) {
          const handler = this.#handlers[current];
          if (!handler || !canRunTaggedHandler(handler, event, tagCache)) {
            continue;
          }
          return handler.Func(event);
        }

        const handler = oneOffHandlerFuncs[current - handlersLen];
        if (!handler) {
          continue;
        }
        return handler(event);
      }
      event.setNextFunc(null);
      return null;
    };

    event.setNextFunc(next);
    return event.Next();
  }

  bind(handler: Handler<T>): string {
    return this.Bind(handler);
  }

  bindFunc(fn: HandlerFunc<T>): string {
    return this.BindFunc(fn);
  }

  unbind(...idsToRemove: string[]): void {
    this.Unbind(...idsToRemove);
  }

  unbindAll(): void {
    this.UnbindAll();
  }

  length(): number {
    return this.Length();
  }

  hasOnlyHandlerId(id: string): boolean {
    return this.HasOnlyHandlerId(id);
  }

  canTriggerOn(tagsToCheck: string[]): boolean {
    return this.CanTriggerOn(tagsToCheck);
  }

  trigger(event: T, ...oneOffHandlerFuncs: HandlerFunc<T>[]): unknown {
    return this.Trigger(event, ...oneOffHandlerFuncs);
  }
}

function canRunTaggedHandler<T extends Resolver>(handler: InternalHandler<T>, event: T, cache: { tags?: string[] }): boolean {
  const tagSet = handler.__pbTagSet;
  if (!tagSet || tagSet.size === 0) {
    return true;
  }

  if (!cache.tags) {
    const tagger = event as unknown as { Tags?: () => string[] };
    cache.tags = typeof tagger.Tags === "function" ? (tagger.Tags() ?? []) : [];
  }

  for (const tag of cache.tags) {
    if (tagSet.has(tag)) {
      return true;
    }
  }

  return false;
}

function generateHookId(): string {
  return randomString(20);
}

function assignHandlerId<T extends Resolver>(handler: Handler<T>, id: string): void {
  const mutable = handler as { id?: string; Id?: string };
  mutable.id = id;
  mutable.Id = id;
}

export { Event };
